import React, { createContext, useContext, useState, ReactNode, useCallback } from "react";

type Language = "es" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, langOverride?: Language) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // General & Navigation
    services: "Services",
    profile: "Profile",
    signOut: "Sign Out",
    languageEs: "Spanish",
    languageEn: "English",
    hubit: "HuBiT",
    login: "Login",
    register: "Register",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    view: "View",
    add: "Add",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    export: "Export",
    import: "Import",
    refresh: "Refresh",
    back: "Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    close: "Close",
    open: "Open",
    home: "Home",
    dashboard: "Dashboard",
    settings: "Settings",
    help: "Help",
    contact: "Contact",
    about: "About",
    whitepaper: "Whitepaper",

    // Service Provider Specific Translations
    serviceProviderPortal: "Service Provider Portal",
    dashboardTitle: "Dashboard Management",
    dashboardDesc: "Access your complete control panel",
    dashboardText: "Manage your services, view requests, track earnings, and monitor your reputation from a centralized dashboard.",
    serviceProfile: "Service Profile",
    manageOfferings: "Manage Your Offerings",
    serviceProfileText: "Create and edit your professional profile, showcase your services, and highlight your expertise to attract more clients.",
    editProfile: "Edit Profile",
    openDashboard: "Open Dashboard",
    popularCategories: "Popular Service Categories",
    
    // Service Categories
    plumbing: "Plumbing",
    electrical: "Electrical",
    painting: "Painting",
    flooring: "Flooring",
    hvac: "HVAC",
    generalRepairs: "General Repairs",

    // Help Center Translations
    helpCenter: "Help Center",
    helpCenterDescription: "Find answers and get support for all your HuBiT needs",
    searchHelp: "Search help articles...",
    popularTopics: "Popular Topics",
    gettingStarted: "Getting Started",
    accountSettings: "Account & Settings",
    paymentsAndBilling: "Payments & Billing",
    servicesManagement: "Services Management",
    communityFeatures: "Community Features",
    troubleshooting: "Troubleshooting",
    safetyAndSecurity: "Safety & Security",
    contactSupport: "Contact Support",
    
    // User Role Specific Help
    helpForCommunityMembers: "Help for Community Members",
    helpForIndividuals: "Help for Individuals",
    helpForServiceProviders: "Help for Service Providers",
    helpForPropertyAdministrators: "Help for Property Administrators",
    
    // Community Members Help
    communityMemberHelp: "Community Member Support",
    howToReportIssues: "How to report community issues",
    howToRequestServices: "How to request services",
    howToRateServices: "How to rate and review services",
    communityPayments: "Community payments and fees",
    neighborCommunication: "Communicating with neighbors",
    
    // Individuals Help
    individualHelp: "Individual User Support",
    findingServices: "Finding and hiring service providers",
    personalServiceRequests: "Managing personal service requests",
    individualPayments: "Payment methods and billing",
    personalAccount: "Managing your personal account",
    
    // Service Providers Help
    serviceProviderHelp: "Service Provider Support",
    createProviderProfile: "Setting up your service provider profile",
    manageServiceOfferings: "Managing your service offerings",
    respondToRequests: "Responding to service requests",
    providerPayments: "Getting paid and payment processing",
    buildReputation: "Building your reputation and ratings",
    
    // Property Administrators Help
    propertyAdminHelp: "Property Administrator Support",
    manageProperties: "Managing multiple properties",
    coordinateServices: "Coordinating community services",
    budgetManagement: "Budget and expense management",
    residentCommunication: "Communicating with residents",
    maintenanceScheduling: "Maintenance and scheduling",
    
    // Common Help Topics
    hbitTokens: "HBIT Tokens and Cryptocurrency",
    howToUseHbit: "How to use HBIT tokens",
    walletSetup: "Setting up your crypto wallet",
    tokenBenefits: "HBIT token benefits",
    paymentOptions: "All payment options",
    
    // Contact and Support
    stillNeedHelp: "Still need help?",
    contactSupportTeam: "Contact our support team",
    emailSupport: "Email Support",
    liveChat: "Live Chat",
    supportHours: "Monday - Friday, 9AM - 6PM",
    
    // FAQ Categories
    frequentlyAsked: "Frequently Asked Questions",
    accountQuestions: "Account Questions",
    paymentQuestions: "Payment Questions",
    serviceQuestions: "Service Questions",
    technicalQuestions: "Technical Questions",
    
    // Status & Notifications
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
    approved: "Approved",
    rejected: "Rejected",
    success: "Success",
    error: "Error",
    warning: "Warning",
    info: "Information",
    loading: "Loading...",
    noData: "No data available",
    noResults: "No results found",
    urgent: "Urgent",
    normal: "Normal",
    low: "Low",
    medium: "Medium",
    high: "High",
    critical: "Critical",
    resolved: "Resolved",
    inProgress: "In Progress",
    closed: "Closed",
    residents: "Residents",

    // Forms
    required: "Required",
    optional: "Optional",
    pleaseSelect: "Please select",
    selectOption: "Select option",
    email: "Email",
    enterEmail: "Enter your email",
    password: "Password",
    enterPassword: "Enter your password",
    confirmPassword: "Confirm Password",
    confirmYourPassword: "Confirm your password",
    fullName: "Full Name",
    enterFullName: "Enter your full name",

    // Auth
    welcomeBack: "Welcome Back",
    loginToAccess: "Log in to access your account",
    forgotPassword: "Forgot your password?",
    dontHaveAccount: "Don't have an account?",
    createAccount: "Create Account",
    registerToStart: "Register to start using our services",
    createPassword: "Create a password",
    alreadyHaveAccount: "Already have an account?",
    
    // Home Page & General Content
    homeTitle: "HuBiT - Community Services Hub",
    homeDescription: "Community services hub with cryptocurrency payments",
    professionalServices: "Community Services Hub",
    whoWeAreTitle: "Who We Are",
    whoWeAreIntro: "We are a comprehensive platform that connects property administrators, service companies and neighbors to provide transparency in the needs of neighborhood communities.",
    ourMission: "Our Mission",
    ourMissionText: "Our mission is to facilitate communication, evaluation and service management, helping companies expand their business while offering total transparency to communities.",
    ourEcosystem: "Our Ecosystem",
    ourEcosystemText: "We create an ecosystem where all participants benefit: administrators can efficiently manage the needs of their communities, service companies can showcase their professionalism and get new clients, and neighbors can rate the services received with total transparency.",
    ourFundamentalValue: "Our Fundamental Value",
    ourFundamentalValueText: "Transparency is our fundamental value, allowing all parties involved to have access to relevant information, facilitating decision-making and improving the quality of life in neighborhood communities.",
    howItWorksTitle: "How It Works",
    howItWorksIntro: "Our platform works as an integrated ecosystem that connects the three fundamental pillars of neighborhood communities:",
    forAdministrators: "For Administrators",
    forAdministratorsText: "We offer digital tools that simplify daily management, allowing to identify needs, request quotes and coordinate services from a single intuitive control panel.",
    forServiceCompanies: "For Service Companies",
    forServiceCompaniesText: "We provide a digital showcase where they can show their professionalism, receive quote requests and obtain verified ratings that boost their reputation.",
    forNeighbors: "For Neighbors",
    forNeighborsText: "We facilitate a platform where they can report incidents, track their resolution in real time and rate the services received with total transparency.",
    ratingsSystem: "Rating System",
    ratingsSystemText: "We implement an evaluation system that allows neighbors to rate services, generating trust and helping to make informed decisions.",
    virtuousCircle: "This integration creates a virtuous circle where all participants benefit: better services for communities, more business opportunities for providers and more efficient management for administrators.",
    whoWeAre: "Who We Are",
    howItWorks: "How It Works",
    features: "Features",

    // User Roles & Dashboards
    communityMember: "Community Member",
    serviceProvider: "Service Provider",
    estateAdministrator: "Estate Administrator",
    particular: "Individual",
    welcomeToDashboard: "Welcome to the Dashboard",
    selectUserType: "Select your user type",
    selectUserTypeDesc: "Choose the option that best describes your profile to access specific functionalities",
    whatsYourRole: "What's your role?",
    communityMemberDesc: "Access exclusive services for your community",
    serviceProviderDesc: "Connect with your community and manage your professional services efficiently",
    estateAdministratorDesc: "Manage properties and communities",
    particularDesc: "Personalized services for individuals",
    accessDashboard: "Access Dashboard",
    communityDashboard: "Community Dashboard",
    providerDashboard: "Provider Dashboard",
    adminDashboard: "Administrator Dashboard",
    particularDashboard: "Individual Dashboard",
    controlPanel: "Control Panel",
    accessAdministratorPanel: "Access Administrator Panel",
    accessProviderPanel: "Access Provider Panel",
    communityMemberLink: "Community Member",
    particularLink: "Individual",
    map: "Map",
    communities: "Communities",
    
    // Financial & Cryptocurrency
    solanaNetwork: "Solana Network",
    creditDebitCards: "Credit/Debit Cards",
    bankTransfers: "Bank Transfers",
    cash: "Cash",
    setupSolanaWallet: "Set up a Solana wallet",
    downloadPhantomWallet: "Download and install Phantom Wallet to securely manage your SOL and HBIT tokens for app subscriptions.",
    clickToPhantom: "Click to go to Phantom →",
    acquireSOL: "Acquire SOL",
    buySOLTokens: "Buy SOL tokens through exchanges or directly in your Phantom wallet for premium app features.",
    clickToLearnBuySOL: "Click to learn how to buy SOL →",
    swapSOLForHBIT: "Swap SOL for HBIT",
    useDecentralizedExchange: "Use a DEX like GMGN to swap your SOL tokens for HBIT to access premium app functionality.",
    clickToSwap: "Click to swap →",
    paymentSystemTitle: "Hybrid Payment System",
    paymentSystemIntro: "We offer multiple payment options: traditional methods for services and cryptocurrency for app premium features",
    fiatCurrencies: "FIAT Currencies",
    fiatDescription: "Traditional and secure payment methods for professional services",
    cryptocurrencies: "Cryptocurrencies", 
    cryptoDescription: "Digital tokens exclusively for app premium features and subscriptions",
    bitcoin: "Bitcoin (BTC)",
    ethereum: "Ethereum (ETH)", 
    binanceCoin: "Binance Coin (BNB)",
    solana: "Solana (SOL)",
    hubitToken: "HUBIT Token",
    hbitDescription: "Our native token for premium app features and loyalty rewards",
    acceptedPayments: "Payment Separation",
    p2pPayments: "Professional Services (EUR only)",
    p2bPayments: "App Subscriptions (Crypto)",
    b2pPayments: "Premium Features (HBIT)",
    b2bPayments: "Business Services (EUR)",
    howToBuyHbitTitle: "How to Buy HBIT",
    howToBuyHbitIntro: "Follow these simple steps to acquire HBIT tokens for premium app features and exclusive benefits",
    hbitBenefits: "Benefits of holding HBIT tokens for app usage",
    benefit1: "Loyalty Airdrops",
    benefit2: "Access to all premium features",
    benefit3: "Enhanced app functionality",
    startUsingHbit: "Start using HBIT",
    learnMore: "Learn more",

    // Whitepaper Translations
    introduction: "Introduction",
    whitepaperDescription: "Comprehensive technical documentation outlining HuBiT's vision, technology, and roadmap for revolutionizing community services",
    whitepaperIntro: "HuBiT represents a paradigm shift in how neighborhood communities manage services, enabling transparent, efficient, and decentralized coordination between residents, administrators, and service providers.",
    visionStatement: "Vision",
    visionText: "To create the world's most transparent and efficient ecosystem for community service management, powered by blockchain technology and driven by community governance.",
    
    // Problem & Solution
    problemStatement: "The Problem",
    lackOfTransparency: "Lack of Transparency",
    transparencyProblem: "Current community management systems lack transparency, making it difficult for residents to understand service decisions and costs.",
    communicationGaps: "Communication Gaps",
    communicationProblem: "Poor communication between administrators, service providers, and residents leads to inefficiencies and misunderstandings.",
    inefficientProcesses: "Inefficient Processes",
    efficiencyProblem: "Manual processes and fragmented systems create delays and increase costs for all stakeholders.",
    
    ourSolution: "Our Solution",
    integratedPlatform: "Integrated Platform",
    platformDescription: "HuBiT provides a comprehensive platform that connects all stakeholders in the community service ecosystem.",
    realTimeTracking: "Real-time service tracking",
    automatedPayments: "Automated payment processing",
    qualityAssurance: "Quality assurance system",
    communityGovernance: "Community governance tools",
    verifiedRatingSystem: "Verified rating system",
    transparentCommunication: "Transparent communication",
    smartAutomation: "Smart automation",
    blockchainSecurity: "Blockchain security",
    serviceRating: "Service Rating",
    serviceRatingDescription: "Advanced rating system that ensures quality and transparency in all service transactions.",
    verifiedReviews: "Verified reviews",
    providerRanking: "Provider ranking",
    transparentHistory: "Transparent history",
    globalCommunity: "Global Community",
    globalCommunityDescription: "Building a worldwide network of trusted service providers and satisfied customers.",
    verifiedProfiles: "Verified profiles",
    trustNetwork: "Trust network",
    socialInteraction: "Social interaction",
    
    // Tokenomics
    tokenomics: "Tokenomics",
    totalSupply: "Total Supply",
    publicPool: "Public Pool",
    communityRewards: "Community Rewards",
    development: "Development",
    team: "Team & Advisors",
    airdropsRewards: "Airdrops & Rewards",
    distributionDetails: "Distribution Details",
    publicPoolDescription: "Tokens available for public acquisition and community rewards",
    teamDescription2: "Reserved for team members and advisors with vesting schedule",
    airdropsRewardsDescription: "Community airdrops and user reward programs",
    marketingDescription: "Marketing campaigns and strategic partnerships",
    
    // Roadmap
    roadmap: "Roadmap",
    roadmapQ1: "Platform MVP launch with basic community management features",
    roadmapQ2: "HBIT token launch and payment integration",
    roadmapQ3: "Advanced governance features and mobile app launch",
    
    // Team
    foundingTeam: "Founding Team",
    teamDescription: "Experienced entrepreneurs with deep expertise in PropTech and blockchain",
    techTeam: "Technical Team",
    techDescription: "Senior developers specializing in blockchain and web technologies",
    advisors: "Advisors",
    advisorsDescription: "Industry leaders from real estate, technology, and finance sectors",
    
    // Key Features
    tableOfContents: "Table of Contents",
    exploreSection: "Explore each section to learn more about HuBiT's comprehensive approach",
    keyHighlights: "Key Highlights",
    transparency: "Transparency",
    transparencyDesc: "Complete visibility into all community service operations",
    blockchainDesc: "Decentralized infrastructure ensuring security and trust",
    communityDriven: "Community Driven",
    communityDesc: "Governance by residents with HBIT token voting rights",
    
    // Service Provider Dashboard Specific
    overview: "Overview",
    myProfile: "My Profile",
    serviceRequests: "Service Requests",
    activeBids: "Active Bids",
    serviceHistory: "Service History",
    reviews: "Reviews",
    earnings: "Earnings",
    
    // Profile Management
    myCompanyProfile: "My Company Profile",
    managePublicInfo: "Manage your company's public information",
    saveChanges: "Save Changes",
    mainInformation: "Main Information",
    businessDetails: "Business Details",
    companyName: "Company Name",
    description: "Description",
    website: "Website",
    phone: "Phone",
    address: "Address",
    taxId: "Tax ID",
    foundedYear: "Founded Year",
    numberOfEmployees: "Number of Employees",
    serviceAreas: "Service Areas (comma separated)",
    certifications: "Certifications (comma separated)",
    offerAllServices: "I offer all services",
    additionalDetails: "Additional Details",
    founded: "Founded",
    employees: "Employees",
    offersAllServices: "Offers all services",
    
    // Professional Services Management
    manageProfessionalServices: "Professional Services",
    manageServicesDesc: "Manage the services you offer and their rates",
    constructionWork: "Construction and repair work",
    interiorExteriorPainting: "Interior and exterior painting",
    electricalInstallations: "Electrical installations and repairs",
    plumbingInstallations: "Plumbing installations and repairs",
    gardenMaintenance: "Garden and green area maintenance",
    elevatorMaintenance: "Elevator maintenance and repair",
    facadeRehabilitation: "Facade rehabilitation and maintenance",
    roofRepair: "Roof repair and maintenance",
    hour: "hour",
    
    // Service Categories (Professional Services)
    masonry: "Masonry",
    gardening: "Gardening",
    elevators: "Elevators",
    facades: "Facades",
    roofs: "Roofs",
    
    // Service Requests
    serviceRequestsTitle: "Service Requests",
    serviceRequestsDesc: "Explore and bid on new work opportunities from communities, assessments and individuals",
    filterByOrigin: "Filter by origin:",
    filterByCategory: "Filter by category:",
    all: "All",
    communityIncident: "Community Incident",
    majorAssessment: "Major Assessment",
    allCategories: "All Categories",
    incident: "Incident",
    assessment: "Assessment",
    approximateBudget: "Approximate budget:",
    deadline: "Deadline:",
    sendQuote: "Send Quote",
    viewDetails: "View Details",
    noServiceRequests: "No service requests",
    noMatchingRequests: "No requests were found that match the selected filters.",
    
    // Bids
    activeBidsTitle: "Active Bids",
    showingAllBids: "Showing all available bids.",
    noBidsInCategory: "No bids available in your service categories.",
    
    // Service History (Provider specific)
    plumbingRepair: "Plumbing Repair",
    electricalInstallation: "Electrical Installation",
    gatesCleaning: "Gates Cleaning",
    generalCleaning: "General Cleaning",
    excellentServiceComment: "Excellent service, very professional and punctual.",
    excellentCommunityServiceComment: "Excellent maintenance service for the community, highly recommended.",
    goodWorkComment: "Good work, clean and efficient installation.",
    goodWorkStairsComment: "Good work cleaning the stairs and common areas.",

    // Community Member Dashboard
    communityMemberDashboard: "Community Member Dashboard",
    myProperties: "My Properties",
    availableServices: "Available Services",
    communityChat: "Community Chat",
    informIssue: "Report Issue",
    communityBudget: "Community Budget",
    contactAdministrator: "Contact Administrator",
    serviceRatings: "Service Ratings",
    configuration: "Configuration",
    recommendations: "Recommendations",
    
    // Community Member Profile Fields
    personalInfo: "Personal Information",
    fullNameComplete: "Full Name",
    emailComplete: "Email",
    phoneComplete: "Phone",
    communityAndHousingInfo: "Community and Housing Information",
    communityNameComplete: "Community Name",
    addressComplete: "Address",
    portalNumberComplete: "Portal Number",
    cityComplete: "City",
    apartmentComplete: "Apartment",
    communityRoleComplete: "Community Role",
    memberSinceComplete: "Member Since",
    
    // Community Member Properties Management
    properties: "Properties",
    owned: "Owned",
    rented: "Rented",
    vacant: "Vacant",
    manageOrganizePropertiesDesc: "Manage and organize all your properties in one place",
    noPropertiesFound: "No properties found",
    addFirstPropertyDesc: "Start by adding your first property to manage it through the platform",
    addFirstProperty: "Add First Property",
    selectedLabel: "Selected",
    selectBtn: "Select",
    editPropertyTitle: "Edit Property",
    addNewPropertyTitle: "Add New Property",
    propertyNameRequired2: "Property Name (Required)",
    addressRequired: "Address (Required)",
    cityRequired2: "City (Required)",
    postalCodeRequired2: "Postal Code (Required)",
    propertyTypeRequired2: "Property Type (Required)",
    statusRequired2: "Status (Required)",
    sizeSqm: "Size (m²)",
    bedroomsLabel: "Bedrooms",
    bathroomsLabel: "Bathrooms",
    yearBuiltLabel: "Year Built",
    communityNameLabel2: "Community Name",
    portalNumberLabel2: "Portal Number",
    apartmentNumberLabel2: "Apartment Number",
    descriptionLabel: "Description",
    propertyNamePlaceholder: "e.g., Madrid Central Apartment",
    addressPlaceholder: "e.g., Calle Gran Vía 123",
    cityPlaceholder: "e.g., Madrid",
    postalCodePlaceholder: "e.g., 28013",
    sizePlaceholder: "85",
    bedroomsPlaceholder: "2",
    bathroomsPlaceholder: "1",
    yearBuiltPlaceholder: "2015",
    communityNamePlaceholder: "e.g., Residencial Los Pinos",
    portalNumberPlaceholder: "e.g., Portal A",
    apartmentNumberPlaceholder: "e.g., 3º A",
    descriptionPlaceholder: "Brief description of the property...",
    updatePropertyBtn: "Update Property",
    createPropertyBtn: "Create Property",
    confirmDeleteProperty: "Are you sure you want to delete this property?",
    
    // Property Types
    apartment: "Apartment",
    house: "House",
    townhouse: "Townhouse",
    condo: "Condo", 
    studio: "Studio",
    
    // Individual Dashboard  
    personalInformation: "Personal Information",
    fullNameLabel: "Full Name",
    emailLabel: "Email",
    phoneLabel: "Phone",
    locationLabel: "Location",
    requestQuote: "Request Quote",
    serviceProviders: "Service Providers",
    myFavorites: "My Favorites",
    myPayments: "My Payments",
    myAwards: "My Awards",
    
    // Estate Administrator Dashboard
    managedCommunities: "Managed Communities",
    totalIncidents: "Total Incidents",
    totalBids: "Total Bids",
    pendingPayments: "Pending Payments",
    thisMonth: "this month",
    vsLastWeek: "vs last week",
    recentBids: "Recent Bids",
    viewAllIncidents: "View All Incidents",
    viewAllBids: "View All Bids",
    
    // Shared translations
    date: "Date",
    service: "Service",
    cost: "Cost",
    provider: "Provider",
    status: "Status",
    actions: "Actions",
    title: "Title",
    type: "Type",
    time: "Time",
    communityGeneric: "Community",
    location: "Location",
    participants: "Participants",
    agenda: "Agenda",
    manage: "Manage",
    request: "Request",
    viewProfile: "View Profile",
    verified: "Verified",
    jobs: "jobs",
    
    // Service Request Specific Content (Provider Dashboard)
    waterLeakGarage: "Water leak in garage",
    waterLeakGarageDesc: "Major leak in main garage pipe.",
    portalLighting: "Portal lighting",
    portalLightingDesc: "Several portal lights not working.",
    completeFacadeRenovation: "Complete facade renovation",
    completeFacadeRenovationDesc: "Comprehensive facade rehabilitation including thermal insulation.",
    roofIntegralRepair: "Comprehensive roof repair",
    roofIntegralRepairDesc: "Complete roof repair including waterproofing.",
    paintCompleteFlat: "Paint complete apartment",
    paintCompleteFlatDesc: "Paint 3-bedroom apartment, 80m2.",
    changeKitchenTap: "Change kitchen tap",
    changeKitchenTapDesc: "Kitchen tap is leaking and needs replacement.",
    abandoCommunity: "Abando Community",
    deustoCommunity: "Deusto Community",
    juanPerez: "Juan Pérez",
    luciaGomez: "Lucía Gómez",
    ercillaStreet: "Ercilla Street 24, Bilbao",
    lehendakariAguirreAv: "Lehendakari Aguirre Avenue 33, Bilbao",
    granViaStreet: "Gran Vía Street 10, Bilbao",
    moyuaSquare: "Moyúa Square 5, Bilbao",
    
    // Additional hardcoded content translations
    discoverTheProcess: "Discover the process",
    knowHubit: "Know HuBiT",
    acquireHbit: "Acquire HBIT",
    importantNote: "Important",
    cryptoExclusiveNote: "Cryptocurrency payments are exclusively for app subscriptions and premium features. Professional services are paid with traditional methods (EUR) according to Spanish regulations.",
    forProfessionalServices: "For professional services",
    professionalServicesNote: "All professional services (cleaning, maintenance, repairs) are paid exclusively in euros according to Spanish regulations.",
    onlyForApp: "Only for using the app",
    appOnlyNote: "Cryptocurrencies are used exclusively for premium subscriptions, advanced features and platform reward tokens.",
    professionalServicesEur: "Professional Services (EUR)",
    appFunctionsCrypto: "App Functions (Crypto)",
    cleaningAndMaintenance: "Cleaning and maintenance",
    repairsAndWorks: "Repairs and construction work",
    gardeningServices: "Gardening services",
    propertyAdministration: "Property administration",
    premiumSubscriptions: "Premium subscriptions",
    rewardTokens: "Reward tokens",
    advancedFeatures: "Advanced features", 
    premiumRatingsAccess: "Premium ratings access",
    paymentSeparationByUse: "Payment Separation by Use",
    paymentSeparationDescription: "HuBiT maintains a clear separation between payments for professional services (EUR) and app functions (crypto)",
    nativeToken: "Native token for premium subscriptions, rating rewards and access to exclusive platform features.",
    specializations: "Specializations",
    schedule: "Schedule",
    notifications: "Notifications",
    electricity: "Electricity",
    
    // Service Provider specific missing translations
    integralServicesMadrid: "Integral Services Madrid",
    companySpecializedMaintenance: "Company specialized in maintenance and renovation services for communities and individuals.",
    alcalaStreetAddress: "Alcalá Street 123, Madrid",
    comprehensiveMaintenance: "Comprehensive maintenance",
    renovations: "Renovations",
    emergencyServices: "Emergency services",
    iso9001: "ISO 9001",
    authorizedInstallerCertificate: "Authorized installer certificate",
    civilLiabilityInsurance: "Civil liability insurance",
    mondayToFridayHours: "Monday to Friday: 8:00 - 18:00, Saturdays: 9:00 - 14:00",
    
    // Community member specific translations that are missing
    addProperty: "Add Property",
    saveLabel: "Save",
    editLabel: "Edit",
    ownerRole: "Owner",
    presidentRole: "President", 
    vicePresidentRole: "Vice-president",
    tenantRole: "Tenant",
    goodMorningQuestion: "Good morning, is anyone available for maintenance questions?",
    adminConfirmation: "Yes, I'm here. What do you need?",
    checkLightingRequest: "Could you check the lighting in the main entrance? It's been flickering.",
    elevatorMaintenanceContract: "Elevator Maintenance Contract",
    preventiveMaintenanceAndEmergencyRepairs: "Preventive maintenance and emergency repairs",
    cleaningService: "Cleaning Service",
    weeklyCleaningCommonAreasPortals: "Weekly cleaning of common areas and portals",
    seasonalMaintenanceGardensGreenAreas: "Seasonal maintenance of gardens and green areas",
    maintenanceCategory: "Maintenance",
    cleaningCategory: "Cleaning", 
    gardeningCategory: "Gardening",
    repairsCategory: "Repairs",
    insuranceCategory: "Insurance",
    commonAreasGardening: "Common Areas Gardening",
    lightingRepair: "Lighting Repair",
    efficientAndCleanWork: "Efficient and clean work",
    excellentFinishVeryProfessional: "Excellent finish, very professional",
    preventiveMaintenance: "Preventive maintenance",
    urgentRepairs: "Urgent repairs",
    modernization: "Modernization",
    landscapeDesign: "Landscape design",
    maintenanceSpec: "Maintenance",
    irrigationSystems: "Irrigation systems",
    gatesDisinfection: "Gates disinfection",
    availabilityLabel: "Available",
    availableServicesTitle: "Available Services",
    availableServicesDesc: "Explore and request services for your community",
    seeDetailsBtn: "See Details",
    requestBtn: "Request",
    communityChatlabel: "Community Chat",
    chatDescription: "Communicate with your neighbors and community administrator",
    writeMessagePlaceholder: "Write your message...",
    scheduleVideoConference: "Schedule Video Conference",
    communityVideoConferenceTitle: "Community Video Conference",
    scheduleVirtualMeetingsDesc: "Schedule and participate in virtual meetings with your community",
    nextMeetingLabel: "Next Meeting",
    ordinaryAssemblyLabel: "Ordinary Assembly",
    meetingDate: "March 15, 2024 - 19:00",
    joinMeetingBtn: "Join Meeting",
    scheduleNewMeetingBtn: "Schedule New Meeting",
    reportIncidentTitle: "Report Incident",
    reportProblemsDesc: "Report problems or incidents in your community",
    incidentTypeLabel: "Type of Incident",
    maintenance: "Maintenance",
    cleaning: "Cleaning", 
    security: "Security",
    other: "Other",
    incidentDescriptionLabel: "Incident Description",
    describeDetailedProblemPlaceholder: "Describe the problem in detail...",
    attachedImages: "Attached Images",
    attachPhotoBtn: "Attach Photo",
    sendIncidentBtn: "Send Incident",
    recentIncidentsLabel: "Recent Incidents",
    garageDoorBrokenText: "Garage door broken",
    reportedAugust2Text: "Reported on August 2",
    solvedLabel: "Solved",
    portalLightingText: "Portal lighting",
    reportedJuly28Text: "Reported on July 28",
    inProcessLabel: "In Process",
    communityContractsTitleLabel: "Community Contracts",
    servicesContractedDesc: "View services contracted by your community",
    activeLabel: "Active",
    pendingLabel: "Pending",
    startDateLabel: "Start Date",
    endDateLabel: "End Date",
    valueLabel: "Value",
    viewContractBtn: "View Contract",
    downloadBtn: "Download",
    communityBudget2024Title: "Community Budget 2024",
    currentStateAnnualBudgetDesc: "Current state of the annual budget",
    totalBudgetLabel: "Total Budget",
    spentLabel: "Spent",
    availableLabel: "Available",
    breakdownByCategoriesTitle: "Breakdown by Categories",
    utilizedLabel: "utilized",
    contactAdministratorTitleLabel: "Contact Administrator",
    communicateDirectlyDesc: "Communicate directly with your community administrator",
    contactInformationLabel: "Contact Information",
    emailLabel2: "Email",
    phoneLabel2: "Phone",
    attentionScheduleLabel: "Attention Schedule",
    mondayToFridaySchedule: "Monday to Friday: 9:00 - 18:00",
    sendMessageBtn: "Send Message",
    subjectLabel: "Subject",
    messageSubjectPlaceholder: "Message subject...",
    messageLabel: "Message",
    writeMessageHerePlaceholder: "Write your message here...",
    filterByStatus: "Filter by status",
    allStatuses: "All Statuses",
    showingServices: "Showing",
    of: "of",
    services: "services",
    sortedBy: "Sorted by",
    ascending: "ascending",
    descending: "descending",
    noServiceHistory: "No service history",
    clearFilters: "Clear filters",
    findServices: "Find Services",
    topRatedProviders: "Top Rated Providers", 
    basedOnCommunityRatings: "Based on community ratings",
    noRecommendations: "No recommendations available",
    serviceRatingsTitleLabel: "Service Ratings",
    yourRatingsCommunitServicesDesc: "Your ratings for community services",
    configurationTitle: "Configuration",
    adjustPreferencesDesc: "Adjust your preferences and settings",
    notificationsLabel: "Notifications",
    emailNotificationsLabel: "Email notifications",
    emailNotificationsDesc: "Receive notifications by email",
    pushNotificationsLabel: "Push notifications", 
    pushNotificationsDesc: "Receive push notifications on your device",
    meetingRemindersLabel: "Meeting reminders",
    videoconferenceAlertsLabel: "Video conference alerts",
    activateBtn: "Activate",
    privacyAndSecurityLabel: "Privacy and Security",
    changePasswordBtn: "Change Password",
    configureTwoFactorAuthBtn: "Configure Two-Factor Authentication",
    downloadMyDataBtn: "Download My Data",
    imagesOnly: "Only images are allowed",
    
    // Additional translations for particular dashboard
    individual: "Particular",
    selectServiceType: "Seleccionar tipo de servicio",
    serviceType: "Tipo de Servicio",
    preferredDate: "Fecha Preferida",
    serviceTitle: "Título del Servicio",
    exampleLeakRepair: "Ejemplo: Reparación de fuga en grifo de cocina",
    detailedDescription: "Descripción Detallada",
    describeServiceNeeded: "Describe el servicio necesario en detalle...",
    requestQuotes: "Solicitar Presupuestos",
    searchProviders: "Buscar proveedores...",
    reviews: "reseñas",
    loadMoreProviders: "Cargar Más Proveedores",
    noFavoriteProviders: "No hay proveedores favoritos",
    addFavoriteProvidersDesc: "Comienza añadiendo tus proveedores de servicios favoritos para acceder a ellos rápidamente",
    exploreProviders: "Explorar Proveedores",
    apartmentInCenter: "Apartamento en el Centro",
    beachHouse: "Casa en la Playa",
    viewDetails: "Ver Detalles",
    manage: "Gestionar",
    loungePainting: "Pintura del Salón",
    noServiceHistoryMessage: "Comienza solicitando servicios para construir tu historial",
    accountPreferences: "Preferencias de Cuenta",
    language: "Idioma",
    spanish: "Español",
    english: "Inglés",
    catalan: "Catalán",
    emailNotifications: "Notificaciones por Email",
    pushNotifications: "Notificaciones Push",
    noPaymentHistory: "No hay historial de pagos disponible",
    basedOnHistory: "Basado en tu historial de servicios",
    emergencyRepairs: "Reparaciones de emergencia",
    newInstallations: "Nuevas instalaciones",
    interiorPaintingSpec: "Pintura interior",
    exteriorPaintingSpec: "Pintura exterior",
    decorativePaintingSpec: "Pintura decorativa",
    installationsSpec: "Instalaciones",
    repairsSpec: "Reparaciones",
    domoticsSpec: "Domótica",
    noAwards: "Aún no hay premios",
    unit: "Unidad",
    noPropertySelected: "Ninguna propiedad seleccionada",
    propertySelected: "Propiedad seleccionada",
    selectAPropertyToManage: "Selecciona una propiedad para gestionar",
    changeProperty: "Cambiar Propiedad",
    carpentry: "Carpintería",
    
    // Estate Administrator specific missing translations
    recentIncidents: "Incidencias Recientes",
    communityMap: "Mapa de Comunidades",
    communitiesOnMap: "Comunidades en el Mapa",
    coordinates: "Coordenadas",
    viewOnMap: "Ver en el Mapa",
    viewDetails: "Ver Detalles",
    contractType: "Tipo de Contrato",
    contractValue: "Valor del Contrato",
    contractStatus: "Estado del Contrato",
    reportedBy: "Reportado Por",
    createdDate: "Fecha de Creación",
    bidder: "Licitador",
    communityContracts: "Contratos de la Comunidad",
    communityIncidents: "Incidencias de la Comunidad",
    communityBids: "Ofertas de la Comunidad",
    noMeetingsThisMonth: "No hay reuniones este mes",
    scheduledMeetings: "Reuniones Programadas",
    communityMeetings: "Reuniones Comunitarias",
    amountStatus: "Importe/Estado",
    action: "Acción",
    description: "Descripción",
    pendingIssues: "Temas Pendientes",
    redirectingToServiceDashboard: "Redirigiendo al panel de servicios",
    goToServiceDashboard: "Ir al Panel de Servicios",
    currentServices: "Servicios Actuales",
    scheduleNewMeeting: "Programar Nueva Reunión",
    meetingTitle: "Título de la Reunión",
    enterMeetingTitle: "Introduce el título de la reunión",
    enterParticipantsEmails: "Introduce los emails de los participantes",
    enterMeetingAgenda: "Introduce la agenda de la reunión",
    scheduleMeeting: "Programar Reunión",
    upcomingMeetings: "Próximas Reuniones",
    communityBudgetDiscussion: "Discusión del Presupuesto Comunitario",
    scheduled: "Programada",
    joinMeeting: "Unirse a la Reunión",
    maintenanceCoordinationMeeting: "Reunión de Coordinación de Mantenimiento"
  },
  es: {
    // General & Navigation
    services: "Servicios",
    profile: "Perfil",
    signOut: "Cerrar sesión",
    languageEs: "Español",
    languageEn: "Inglés",
    hubit: "HuBiT",
    login: "Iniciar sesión",
    register: "Registrarse",
    save: "Guardar",
    cancel: "Cancelar",
    edit: "Editar",
    delete: "Eliminar",
    view: "Ver",
    add: "Añadir",
    search: "Buscar",
    filter: "Filtrar",
    sort: "Ordenar",
    export: "Exportar",
    import: "Importar",
    refresh: "Actualizar",
    back: "Volver",
    next: "Siguiente",
    previous: "Anterior",
    submit: "Enviar",
    close: "Cerrar",
    open: "Abrir",
    home: "Inicio",
    dashboard: "Panel de Control",
    settings: "Configuración",
    help: "Ayuda",
    contact: "Contacto",
    about: "Acerca de",
    whitepaper: "Libro Blanco",

    // Service Provider Specific Translations
    serviceProviderPortal: "Portal de Proveedor de Servicios",
    dashboardTitle: "Gestión del Panel",
    dashboardDesc: "Accede a tu panel de control completo",
    dashboardText: "Gestiona tus servicios, ve las solicitudes, rastrea tus ganancias y monitorea tu reputación desde un panel centralizado.",
    serviceProfile: "Perfil de Servicios",
    manageOfferings: "Gestiona tus Ofertas",
    serviceProfileText: "Crea y edita tu perfil profesional, muestra tus servicios y destaca tu experiencia para atraer más clientes.",
    editProfile: "Editar Perfil",
    openDashboard: "Abrir Panel",
    popularCategories: "Categorías de Servicios Populares",
    
    // Service Categories
    plumbing: "Fontanería",
    electrical: "Electricidad",
    painting: "Pintura",
    flooring: "Suelos",
    hvac: "Climatización",
    generalRepairs: "Reparaciones Generales",

    // Help Center Translations
    helpCenter: "Centro de Ayuda",
    helpCenterDescription: "Encuentra respuestas y soporte para todas tus necesidades de HuBiT",
    searchHelp: "Buscar artículos de ayuda...",
    popularTopics: "Temas Populares",
    gettingStarted: "Comenzando",
    accountSettings: "Cuenta y Configuración",
    paymentsAndBilling: "Pagos y Facturación",
    servicesManagement: "Gestión de Servicios",
    communityFeatures: "Características Comunitarias",
    troubleshooting: "Solución de Problemas",
    safetyAndSecurity: "Seguridad y Privacidad",
    contactSupport: "Contactar Soporte",
    
    // User Role Specific Help
    helpForCommunityMembers: "Ayuda para Miembros de la Comunidad",
    helpForIndividuals: "Ayuda para Particulares",
    helpForServiceProviders: "Ayuda para Proveedores de Servicios",
    helpForPropertyAdministrators: "Ayuda para Administradores de Fincas",
    
    // Community Members Help
    communityMemberHelp: "Soporte para Miembros de la Comunidad",
    howToReportIssues: "Cómo reportar incidencias comunitarias",
    howToRequestServices: "Cómo solicitar servicios",
    howToRateServices: "Cómo calificar y valorar servicios",
    communityPayments: "Pagos y tasas comunitarias",
    neighborCommunication: "Comunicación con vecinos",
    
    // Individuals Help
    individualHelp: "Soporte para Particulares",
    findingServices: "Encontrar y contratar proveedores de servicios",
    personalServiceRequests: "Gestionar solicitudes de servicios personales",
    individualPayments: "Métodos de pago y facturación",
    personalAccount: "Gestionar tu cuenta personal",
    
    // Service Providers Help
    serviceProviderHelp: "Soporte para Proveedores de Servicios",
    createProviderProfile: "Configurar tu perfil de proveedor de servicios",
    manageServiceOfferings: "Gestionar tus ofertas de servicios",
    respondToRequests: "Responder a solicitudes de servicios",
    providerPayments: "Obtener pagos y procesar cobros",
    buildReputation: "Construir tu reputación y calificaciones",
    
    // Property Administrators Help
    propertyAdminHelp: "Soporte para Administradores de Fincas",
    manageProperties: "Gestionar múltiples propiedades",
    coordinateServices: "Coordinar servicios comunitarios",
    budgetManagement: "Gestión de presupuestos y gastos",
    residentCommunication: "Comunicarse con residentes",
    maintenanceScheduling: "Mantenimiento y programación",
    
    // Common Help Topics
    hbitTokens: "Tokens HBIT y Criptomonedas",
    howToUseHbit: "Cómo usar tokens HBIT",
    walletSetup: "Configurar tu billetera criptográfica",
    tokenBenefits: "Beneficios de los tokens HBIT",
    paymentOptions: "Todas las opciones de pago",
    
    // Contact and Support
    stillNeedHelp: "¿Todavía necesitas ayuda?",
    contactSupportTeam: "Contacta con nuestro equipo de soporte",
    emailSupport: "Soporte por Email",
    liveChat: "Chat en Vivo",
    supportHours: "Lunes - Viernes, 9AM - 6PM",
    
    // FAQ Categories
    frequentlyAsked: "Preguntas Frecuentes",
    accountQuestions: "Preguntas de Cuenta",
    paymentQuestions: "Preguntas de Pagos",
    serviceQuestions: "Preguntas de Servicios",
    technicalQuestions: "Preguntas Técnicas",
    
    // Status & Notifications
    active: "Activo",
    inactive: "Inactivo",
    pending: "Pendiente",
    completed: "Completado",
    cancelled: "Cancelado",
    approved: "Aprobado",
    rejected: "Rechazado",
    success: "Éxito",
    error: "Error",
    warning: "Advertencia",
    info: "Información",
    loading: "Cargando...",
    noData: "No hay datos disponibles",
    noResults: "No se encontraron resultados",
    urgent: "Urgente",
    normal: "Normal",
    low: "Baja",
    medium: "Medio",
    high: "Alto",
    critical: "Crítico",
    resolved: "Resueltas",
    inProgress: "En Progreso",
    closed: "Cerradas",
    residents: "Residentes",

    // Forms
    required: "Requerido",
    optional: "Opcional",
    pleaseSelect: "Por favor selecciona",
    selectOption: "Seleccionar opción",
    email: "Correo electrónico",
    enterEmail: "Introduce tu correo electrónico",
    password: "Contraseña",
    enterPassword: "Introduce tu contraseña",
    confirmPassword: "Confirmar contraseña",
    confirmYourPassword: "Confirma tu contraseña",
    fullName: "Nombre completo",
    enterFullName: "Introduce tu nombre completo",

    // Auth
    welcomeBack: "Bienvenido de nuevo",
    loginToAccess: "Inicia sesión para acceder a tu cuenta",
    forgotPassword: "¿Olvidaste tu contraseña?",
    dontHaveAccount: "¿No tienes una cuenta?",
    createAccount: "Crear cuenta",
    registerToStart: "Regístrate para empezar a usar nuestros servicios",
    createPassword: "Crea una contraseña",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    
    // Home Page & General Content
    homeTitle: "HuBiT - Hub de servicios comunitarios",
    homeDescription: "Hub de servicios comunitarios con pagos en criptomonedas",
    professionalServices: "Hub de servicios comunitarios",
    whoWeAreTitle: "Quiénes Somos",
    whoWeAreIntro: "Somos una plataforma integral que conecta a administradores de fincas, empresas de servicios y vecinos para brindar transparencia en las necesidades de las comunidades de vecinos.",
    ourMission: "Nuestra Misión",
    ourMissionText: "Nuestra misión es facilitar la comunicación, valoración y gestión de servicios, ayudando a las empresas a expandir su negocio mientras ofrecemos total transparencia a las comunidades.",
    ourEcosystem: "Nuestro Ecosistema",
    ourEcosystemText: "Creamos un ecosistema donde todos los participantes se benefician: los administradores pueden gestionar eficientemente las necesidades de sus comunidades, las empresas de servicios pueden mostrar su profesionalidad y obtener nuevos clientes, y los vecinos pueden valorar los servicios recibidos con total transparencia.",
    ourFundamentalValue: "Nuestro Valor Fundamental",
    ourFundamentalValueText: "La transparencia es nuestro valor fundamental, permitiendo que todas las partes involucradas tengan acceso a la información relevante, facilitando la toma de decisiones y mejorando la calidad de vida en las comunidades de vecinos.",
    howItWorksTitle: "Cómo Funciona",
    howItWorksIntro: "Nuestra plataforma funciona como un ecosistema integrado que conecta a los tres pilares fundamentales de las comunidades de vecinos:",
    forAdministrators: "Para Administradores",
    forAdministratorsText: "Ofrecemos herramientas digitales que simplifican la gestión diaria, permitiendo identificar necesidades, solicitar presupuestos y coordinar servicios desde un único panel de control intuitivo.",
    forServiceCompanies: "Para Empresas de Servicios",
    forServiceCompaniesText: "Proporcionamos un escaparate digital donde mostrar su profesionalidad, recibir solicitudes de presupuestos y obtener valoraciones verificadas que impulsan su reputación.",
    forNeighbors: "Para Vecinos",
    forNeighborsText: "Facilitamos una plataforma donde pueden reportar incidencias, seguir su resolución en tiempo real y valorar los servicios recibidos con total transparencia.",
    ratingsSystem: "Sistema de Valoraciones",
    ratingsSystemText: "Implementamos un sistema de evaluación que permite a los vecinos calificar los servicios, generando confianza y ayudando a tomar decisiones informadas.",
    virtuousCircle: "Esta integración crea un círculo virtuoso donde todos los participantes se benefician: mejores servicios para las comunidades, más oportunidades de negocio para los proveedores y una gestión más eficiente para los administradores.",
    whoWeAre: "Who We Are",
    howItWorks: "How It Works",
    features: "Features",

    // User Roles & Dashboards
    communityMember: "Miembro de la Comunidad",
    serviceProvider: "Proveedor de Servicios",
    estateAdministrator: "Administrador de Fincas",
    particular: "Particular",
    welcomeToDashboard: "Bienvenido al Panel de Control",
    selectUserType: "Selecciona tu tipo de usuario",
    selectUserTypeDesc: "Elige la opción que mejor describa tu perfil para acceder a las funcionalidades específicas",
    whatsYourRole: "¿Cuál es tu rol?",
    communityMemberDesc: "Accede a servicios exclusivos para tu comunidad",
    serviceProviderDesc: "Conéctate con tu comunidad y gestiona tus servicios profesionales de manera eficiente",
    estateAdministratorDesc: "Administra propiedades y comunidades",
    particularDesc: "Servicios personalizados para particulares",
    accessDashboard: "Acceder al Panel",
    communityDashboard: "Panel de Comunidad",
    providerDashboard: "Panel de Proveedor",
    adminDashboard: "Panel de Administrador",
    particularDashboard: "Panel Particular",
    controlPanel: "Panel de Control",
    accessAdministratorPanel: "Acceder al Panel de Administrador",
    accessProviderPanel: "Acceder al Panel de Proveedor",
    communityMemberLink: "Miembro de la Comunidad",
    particularLink: "Particular",
    map: "Mapa",
    communities: "Comunidades",
    
    // Financial & Cryptocurrency
    solanaNetwork: "Red Solana",
    creditDebitCards: "Tarjetas de Crédito/Débito",
    bankTransfers: "Transferencias Bancarias",
    cash: "Efectivo",
    setupSolanaWallet: "Configura una billetera Solana",
    downloadPhantomWallet: "Descarga e instala Phantom Wallet para gestionar tus tokens SOL y HBIT de forma segura para suscripciones de la app.",
    clickToPhantom: "Haz clic para ir a Phantom →",
    acquireSOL: "Adquiere SOL",
    buySOLTokens: "Compra tokens SOL a través de exchanges o directamente en tu billetera Phantom para características premium de la app.",
    clickToLearnBuySOL: "Haz clic para aprender a comprar SOL →",
    swapSOLForHBIT: "Intercambia SOL por HBIT",
    useDecentralizedExchange: "Utiliza un DEX como GMGN para intercambiar tus tokens SOL por HBIT para acceder a funcionalidades premium de la app.",
    clickToSwap: "Haz clic para intercambiar →",
    paymentSystemTitle: "Sistema de Pagos Híbrido",
    paymentSystemIntro: "Ofrecemos múltiples opciones de pago: métodos tradicionales para servicios y criptomonedas para características premium de la app",
    fiatCurrencies: "Monedas FIAT",
    fiatDescription: "Métodos de pago tradicionales y seguros para servicios profesionales",
    cryptocurrencies: "Criptomonedas",
    cryptoDescription: "Tokens digitales exclusivamente para características premium de la app y suscripciones",
    bitcoin: "Bitcoin (BTC)",
    ethereum: "Ethereum (ETH)",
    binanceCoin: "Binance Coin (BNB)",
    solana: "Solana (SOL)",
    hubitToken: "Token HUBIT",
    hbitDescription: "Nuestro token nativo para características premium de la app y recompensas de fidelidad",
    acceptedPayments: "Separación de Pagos",
    p2pPayments: "Servicios Profesionales (solo EUR)",
    p2bPayments: "Suscripciones de App (Cripto)",
    b2pPayments: "Características Premium (HBIT)",
    b2bPayments: "Servicios Empresariales (EUR)",
    howToBuyHbitTitle: "Cómo Comprar HBIT",
    howToBuyHbitIntro: "Sigue estos sencillos pasos para adquirir tokens HBIT para características premium de la app y beneficios exclusivos",
    hbitBenefits: "Beneficios de mantener tokens HBIT para uso de la app",
    benefit1: "Regalos por fidelidad",
    benefit2: "Acceso a todas las funcionalidades premium",
    benefit3: "Funcionalidad mejorada de la app",
    startUsingHbit: "Comenzar a usar HBIT",
    learnMore: "Saber más",

    // Whitepaper Translations
    introduction: "Introducción",
    whitepaperDescription: "Documentación técnica completa que describe la visión, tecnología y roadmap de HuBiT para revolucionar los servicios comunitarios",
    whitepaperIntro: "HuBiT representa un cambio de paradigma en cómo las comunidades de vecinos gestionan sus servicios, permitiendo una coordinación transparente, eficiente y descentralizada entre residentes, administradores y proveedores de servicios.",
    visionStatement: "Declaración de Visión",
    visionText: "Crear el ecosistema de servicios comunitarios más transparente y eficiente del mundo, impulsado por tecnología blockchain y gobernado por la comunidad.",
    
    // Problem & Solution
    problemStatement: "Enunciado del Problema",
    lackOfTransparency: "Falta de Transparencia",
    transparencyProblem: "Los sistemas actuales de gestión comunitaria carecen de transparencia, dificultando que los vecinos entiendan las decisiones y costos de los servicios.",
    communicationGaps: "Fallas en la Comunicación",
    communicationProblem: "La comunicación deficiente entre administradores, proveedores de servicios y vecinos genera ineficiencias y confusiones.",
    inefficientProcesses: "Procesos Ineficientes",
    efficiencyProblem: "Los procesos manuales y sistemas fragmentados generan retrasos y aumentan los costos para todos los involucrados.",
    
    ourSolution: "Nuestra Solución",
    integratedPlatform: "Plataforma Integrada",
    platformDescription: "HuBiT ofrece una plataforma completa que conecta a todos los participantes del ecosistema de servicios comunitarios.",
    realTimeTracking: "Seguimiento en tiempo real de los servicios",
    automatedPayments: "Procesamiento automático de pagos",
    qualityAssurance: "Sistema de aseguramiento de calidad",
    communityGovernance: "Herramientas de gobernanza comunitaria",
    verifiedRatingSystem: "Sistema de valoración verificado",
    transparentCommunication: "Comunicación transparente",
    smartAutomation: "Automatización inteligente",
    blockchainSecurity: "Seguridad blockchain",
    serviceRating: "Valoración de Servicios",
    serviceRatingDescription: "Sistema avanzado de valoración que garantiza calidad y transparencia en todas las transacciones de servicios.",
    verifiedReviews: "Reseñas verificadas",
    providerRanking: "Ranking de proveedores",
    transparentHistory: "Historial transparente",
    globalCommunity: "Comunidad Global",
    globalCommunityDescription: "Construyendo una red mundial de proveedores de servicios confiables y clientes satisfechos.",
    verifiedProfiles: "Perfiles verificados",
    trustNetwork: "Red de confianza",
    socialInteraction: "Interacción social",
    
    // Tokenomics
    tokenomics: "Tokenomics",
    totalSupply: "Suministro Total",
    publicPool: "Pool Público",
    communityRewards: "Recompensas Comunitarias",
    development: "Desarrollo",
    team: "Equipo & Asesores",
    airdropsRewards: "Airdrops & Recompensas",
    distributionDetails: "Detalles de Distribución",
    publicPoolDescription: "Tokens disponibles para adquisición pública y recompensas comunitarias",
    teamDescription2: "Reservado para miembros del equipo y asesores con cronograma de vesting",
    airdropsRewardsDescription: "Airdrops comunitarios y programas de recompensas para usuarios",
    marketingDescription: "Campañas de marketing y alianzas estratégicas",
    
    // Additional whitepaper content
    hubFuture: "El Futuro de los Servicios Comunitarios",
    hubFutureDescription: "HuBiT está pioneriando la próxima generación de gestión de servicios comunitarios, creando un ecosistema transparente, eficiente y descentralizado que beneficia a todos los participantes.",
    backToTop: "Volver Arriba",
    
    // Technology
    technologyStack: "Stack Tecnológico",
    blockchain: "Infraestructura Blockchain",
    blockchainDescription: "Construido en Solana para transacciones rápidas y de bajo costo con funcionalidad de smart contracts.",
    webPlatform: "Plataforma Web",
    webDescription: "Aplicación web moderna construida con Next.js, TypeScript y funcionalidades en tiempo real.",
    
    // Roadmap
    roadmap: "Roadmap",
    roadmapQ1: "Lanzamiento de la plataforma MVP con características básicas de gestión comunitaria",
    roadmapQ2: "Lanzamiento del token HBIT y integración de pagos",
    roadmapQ3: "Características de gobernanza avanzadas y lanzamiento de la app móvil",
    
    // Team
    foundingTeam: "Equipo Fundador",
    teamDescription: "Emprendedores experimentados con amplia experiencia en PropTech y blockchain",
    techTeam: "Equipo Técnico",
    techDescription: "Desarrolladores senior especializados en blockchain y tecnologías web",
    advisors: "Asesores",
    advisorsDescription: "Líderes del sector de inmobiliario, tecnología y finanzas",
    
    // Key Features
    tableOfContents: "Tabla de Contenidos",
    exploreSection: "Explora cada sección para conocer más sobre nuestro enfoque integral",
    keyHighlights: "Destacados",
    transparency: "Transparencia",
    transparencyDesc: "Visibilidad completa en todas las operaciones de servicios comunitarios",
    blockchainDesc: "Infraestructura descentralizada garantizando seguridad y confianza",
    communityDriven: "Dirigido por la Comunidad",
    communityDesc: "Gobierno por vecinos con derechos de votación de tokens HBIT",
    
    // Service Provider Dashboard Specific  
    overview: "Resumen",
    myProfile: "Mi Perfil",
    serviceRequests: "Solicitudes de Servicio",
    activeBids: "Ofertas Activas",
    serviceHistory: "Historial de Servicios",
    reviews: "Reseñas",
    earnings: "Ganancias",
    
    // Profile Management
    myCompanyProfile: "Mi Perfil de Empresa",
    managePublicInfo: "Gestiona la información pública de tu empresa",
    saveChanges: "Guardar Cambios",
    mainInformation: "Información Principal",
    businessDetails: "Detalles del Negocio",
    companyName: "Nombre de la empresa",
    description: "Descripción",
    website: "Página Web",
    phone: "Teléfono", 
    address: "Dirección",
    taxId: "CIF",
    foundedYear: "Año de fundación",
    numberOfEmployees: "Nº de empleados",
    serviceAreas: "Áreas de servicio (separadas por coma)",
    certifications: "Certificaciones (separadas por coma)",
    offerAllServices: "Ofrezco todos los servicios",
    additionalDetails: "Detalles Adicionales",
    founded: "Fundación",
    employees: "Empleados",
    offersAllServices: "Ofrece todos los servicios",
    
    // Professional Services
    manageProfessionalServices: "Servicios Profesionales",
    manageServicesDesc: "Gestiona los servicios que ofreces y sus tarifas",
    constructionWork: "Trabajos de construcción y reparación",
    interiorExteriorPainting: "Pintura interior y exterior",
    electricalInstallations: "Instalaciones y reparaciones eléctricas",
    plumbingInstallations: "Instalaciones y reparaciones de fontanería",
    gardenMaintenance: "Mantenimiento de jardines y zonas verdes",
    elevatorMaintenance: "Mantenimiento y reparación de ascensores",
    facadeRehabilitation: "Rehabilitación y mantenimiento de fachadas", 
    roofRepair: "Reparación y mantenimiento de cubiertas",
    hour: "hora",
    
    // Service Categories (Professional Services)
    masonry: "Albañilería",
    gardening: "Jardinería",
    elevators: "Ascensores",
    facades: "Fachadas",
    roofs: "Tejados",
    
    // Service Requests
    serviceRequestsTitle: "Solicitudes de Servicio",
    serviceRequestsDesc: "Explora y oferta en nuevas oportunidades de trabajo de comunidades, derramas y particulares",
    filterByOrigin: "Filtrar por origen:",
    filterByCategory: "Filtrar por categoría:",
    all: "Todos",
    communityIncident: "Incidencia Comunidad",
    majorAssessment: "Derrama Importante", 
    allCategories: "Todas",
    incident: "Incidencia",
    assessment: "Derrama", 
    approximateBudget: "Presupuesto aprox:",
    deadline: "Fecha límite:",
    sendQuote: "Enviar Presupuesto",
    viewDetails: "Ver Detalles",
    noServiceRequests: "No hay solicitudes de servicio",
    noMatchingRequests: "No se encontraron solicitudes que coincidan con los filtros seleccionados.",
    
    // Bids  
    activeBidsTitle: "Ofertas Activas",
    showingAllBids: "Mostrando todas las ofertas disponibles.",
    noBidsInCategory: "No hay ofertas disponibles en tus categorías de servicio.",
    
    // Service History (Provider specific)
    plumbingRepair: "Reparación de Fontanería",
    electricalInstallation: "Instalación Eléctrica", 
    gatesCleaning: "Limpieza de Portales",
    generalCleaning: "Limpieza General",
    excellentServiceComment: "Excelente servicio, muy profesional y puntual.",
    excellentCommunityServiceComment: "Excelente servicio de mantenimiento para la comunidad, muy recomendable.",
    goodWorkComment: "Buen trabajo, instalación limpia y eficiente.",
    goodWorkStairsComment: "Buen trabajo limpiando las escaleras y zonas comunes.",
    
    // Community Member Dashboard
    communityMemberDashboard: "Panel de Miembro de la Comunidad",
    myProperties: "Mis Propiedades",
    availableServices: "Servicios Disponibles",
    communityChat: "Chat Comunitario",
    informIssue: "Informar Incidencia",
    communityBudget: "Presupuesto Comunitario",
    contactAdministrator: "Contactar Administrador",
    serviceRatings: "Valoraciones de Servicios",
    configuration: "Configuración",
    recommendations: "Recomendaciones",
    
    // Community Member Profile Fields
    personalInfo: "Información Personal",
    fullNameComplete: "Nombre Completo",
    emailComplete: "Correo Electrónico",
    phoneComplete: "Teléfono",
    communityAndHousingInfo: "Información de Comunidad y Vivienda",
    communityNameComplete: "Nombre de la Comunidad",
    addressComplete: "Dirección",
    portalNumberComplete: "Número de Portal",
    cityComplete: "Ciudad",
    apartmentComplete: "Apartamento",
    communityRoleComplete: "Rol en la Comunidad",
    memberSinceComplete: "Miembro desde",
    
    // Community Member Properties Management
    properties: "Propiedades",
    owned: "Propiedad",
    rented: "Alquilado",
    vacant: "Vacío",
    manageOrganizePropertiesDesc: "Gestiona y organiza todas tus propiedades en un solo lugar",
    noPropertiesFound: "No se encontraron propiedades",
    addFirstPropertyDesc: "Comienza añadiendo tu primera propiedad para gestionarla a través de la plataforma",
    addFirstProperty: "Añadir Primera Propiedad",
    selectedLabel: "Seleccionada",
    selectBtn: "Seleccionar",
    editPropertyTitle: "Editar Propiedad",
    addNewPropertyTitle: "Añadir Nueva Propiedad",
    propertyNameRequired2: "Nombre de la Propiedad (Requerido)",
    addressRequired: "Dirección (Requerido)",
    cityRequired2: "Ciudad (Requerido)",
    postalCodeRequired2: "Código Postal (Requerido)",
    propertyTypeRequired2: "Tipo de Propiedad (Requerido)",
    statusRequired2: "Estado (Requerido)",
    sizeSqm: "Tamaño (m²)",
    bedroomsLabel: "Dormitorios",
    bathroomsLabel: "Baños",
    yearBuiltLabel: "Año de Construcción",
    communityNameLabel2: "Nombre de la Comunidad",
    portalNumberLabel2: "Número de Portal",
    apartmentNumberLabel2: "Número de Apartamento",
    descriptionLabel: "Descripción",
    propertyNamePlaceholder: "ej., Apartamento Madrid Centro",
    addressPlaceholder: "ej., Calle Gran Vía 123",
    cityPlaceholder: "ej., Madrid",
    postalCodePlaceholder: "ej., 28013",
    sizePlaceholder: "85",
    bedroomsPlaceholder: "2",
    bathroomsPlaceholder: "1",
    yearBuiltPlaceholder: "2015",
    communityNamePlaceholder: "ej., Residencial Los Pinos",
    portalNumberPlaceholder: "ej., Portal A",
    apartmentNumberPlaceholder: "ej., 3ºA",
    descriptionPlaceholder: "Breve descripción de la propiedad...",
    updatePropertyBtn: "Actualizar Propiedad",
    createPropertyBtn: "Crear Propiedad",
    confirmDeleteProperty: "¿Estás seguro de que quieres eliminar esta propiedad?",
    
    // Property Types
    apartment: "Apartamento",
    house: "Casa",
    townhouse: "Casa Adosada",
    condo: "Condominio",
    studio: "Estudio",
    
    // Individual Dashboard  
    personalInformation: "Información Personal",
    fullNameLabel: "Nombre Completo",
    emailLabel: "Correo Electrónico",
    phoneLabel: "Teléfono",
    locationLabel: "Ubicación",
    requestQuote: "Solicitar Presupuesto",
    serviceProviders: "Proveedores de Servicios",
    myFavorites: "Mis Favoritos",
    myPayments: "Mis Pagos",
    myAwards: "Mis Premios",
    
    // Estate Administrator Dashboard
    managedCommunities: "Comunidades Gestionadas",
    totalIncidents: "Total de Incidencias",
    totalBids: "Total de Ofertas",
    pendingPayments: "Pagos Pendientes",
    thisMonth: "este mes",
    vsLastWeek: "vs la semana pasada",
    recentBids: "Ofertas Recientes",
    viewAllIncidents: "Ver Todas las Incidencias",
    viewAllBids: "Ver Todas las Ofertas",
    
    // Shared translations
    date: "Fecha",
    service: "Servicio",
    cost: "Coste",
    provider: "Proveedor",
    status: "Estado",
    actions: "Acciones",
    title: "Título",
    type: "Tipo",
    time: "Hora",
    community: "Comunidad",
    location: "Ubicación",
    participants: "Participantes",
    agenda: "Agenda",
    manage: "Gestionar",
    request: "Solicitar",
    viewProfile: "Ver Perfil",
    verified: "Verificado",
    jobs: "trabajos",
    
    // Service Request Specific Content (Provider Dashboard)
    waterLeakGarage: "Fuga de agua en el garaje",
    waterLeakGarageDesc: "Fuga importante en tubería principal del garaje.",
    portalLighting: "Iluminación del portal",
    portalLightingDesc: "Varias luces del portal no funcionan.",
    completeFacadeRenovation: "Renovación completa de fachada",
    completeFacadeRenovationDesc: "Rehabilitación integral de la fachada del edificio incluyendo aislamiento térmico.",
    roofIntegralRepair: "Reparación integral del tejado",
    roofIntegralRepairDesc: "Reparación completa del tejado incluyendo impermeabilización.",
    paintCompleteFlat: "Pintar piso completo",
    paintCompleteFlatDesc: "Pintar piso de 3 habitaciones, 80m2.",
    changeKitchenTap: "Cambiar grifo de la cocina",
    changeKitchenTapDesc: "El grifo de la cocina gotea y necesita ser reemplazado.",
    abandoCommunity: "Comunidad Abando",
    deustoCommunity: "Comunidad Deusto",
    juanPerez: "Juan Pérez",
    luciaGomez: "Lucía Gómez",
    ercillaStreet: "Calle Ercilla 24, Bilbao",
    lehendakariAguirreAv: "Avenida Lehendakari Aguirre 33, Bilbao",
    granViaStreet: "Calle Gran Vía 10, Bilbao",
    moyuaSquare: "Plaza Moyúa 5, Bilbao",
    
    // Additional hardcoded content translations
    discoverTheProcess: "Descubrir el proceso",
    knowHubit: "Conocer HuBiT",
    acquireHbit: "Adquirir HBIT",
    importantNote: "Importante",
    cryptoExclusiveNote: "Los pagos con criptomonedas son exclusivamente para suscripciones de la app y características premium. Los servicios profesionales se pagan con métodos tradicionales (EUR) según la normativa española.",
    forProfessionalServices: "Para servicios profesionales",
    professionalServicesNote: "Todos los servicios profesionales (limpieza, mantenimiento, reparaciones) se pagan exclusivamente en euros según la normativa española.",
    onlyForApp: "Solo para usar la app",
    appOnlyNote: "Las criptomonedas se usan exclusivamente para suscripciones premium, características avanzadas y tokens de recompensa de la plataforma.",
    professionalServicesEur: "Servicios Profesionales (EUR)",
    appFunctionsCrypto: "Funciones de la App (Cripto)",
    cleaningAndMaintenance: "Limpieza y mantenimiento",
    repairsAndWorks: "Reparaciones y obras",
    gardeningServices: "Servicios de jardinería",
    propertyAdministration: "Administración de fincas",
    premiumSubscriptions: "Suscripciones premium",
    rewardTokens: "Tokens de recompensa",
    advancedFeatures: "Características avanzadas", 
    premiumRatingsAccess: "Acceso premium a valoraciones",
    paymentSeparationByUse: "Separación de Pagos por Uso",
    paymentSeparationDescription: "HuBiT mantiene una clara separación entre pagos para servicios profesionales (EUR) y funciones de la app (cripto)",
    nativeToken: "Token nativo para suscripciones premium, recompensas de valoración y acceso a características exclusivas de la plataforma.",
    specializations: "Especializaciones",
    schedule: "Horario",
    notifications: "Notificaciones",
    electricity: "Electricidad",
    
    // Service Provider specific missing translations
    integralServicesMadrid: "Servicios Integrales Madrid",
    companySpecializedMaintenance: "Empresa especializada en servicios de mantenimiento y reformas para comunidades y particulares.",
    alcalaStreetAddress: "Calle Alcalá 123, Madrid",
    comprehensiveMaintenance: "Mantenimiento integral",
    renovations: "Reformas",
    emergencyServices: "Servicios urgentes",
    iso9001: "ISO 9001",
    authorizedInstallerCertificate: "Certificado instalador autorizado",
    civilLiabilityInsurance: "Seguro responsabilidad civil",
    mondayToFridayHours: "Lunes a Viernes: 8:00 - 18:00, Sábados: 9:00 - 14:00",
    
    // Community member specific translations that are missing
    addProperty: "Añadir Propiedad",
    saveLabel: "Guardar",
    editLabel: "Editar", 
    ownerRole: "Propietario",
    presidentRole: "Presidente",
    vicePresidentRole: "Vicepresidente",
    tenantRole: "Inquilino",
    goodMorningQuestion: "Buenos días, ¿hay alguien disponible para consultas de mantenimiento?",
    adminConfirmation: "Sí, estoy aquí. ¿Qué necesitas?",
    checkLightingRequest: "¿Podrías revisar la iluminación en la entrada principal? Ha estado parpadeando.",
    elevatorMaintenanceContract: "Contrato de Mantenimiento de Ascensores",
    preventiveMaintenanceAndEmergencyRepairs: "Mantenimiento preventivo y reparaciones de emergencia",
    cleaningService: "Servicio de Limpieza",
    weeklyCleaningCommonAreasPortals: "Limpieza semanal de áreas comunes y portales",
    seasonalMaintenanceGardensGreenAreas: "Mantenimiento estacional de jardines y zonas verdes",
    maintenanceCategory: "Mantenimiento",
    cleaningCategory: "Limpieza", 
    gardeningCategory: "Jardinería",
    repairsCategory: "Reparaciones",
    insuranceCategory: "Seguros",
    commonAreasGardening: "Jardinería de Áreas Comunes",
    lightingRepair: "Reparación de Iluminación",
    efficientAndCleanWork: "Trabajo eficiente y limpio",
    excellentFinishVeryProfessional: "Excelente acabado, muy profesional",
    preventiveMaintenance: "Mantenimiento preventivo",
    urgentRepairs: "Reparaciones urgentes",
    modernization: "Modernización",
    landscapeDesign: "Diseño paisajístico",
    maintenanceSpec: "Mantenimiento",
    irrigationSystems: "Sistemas de riego",
    gatesDisinfection: "Desinfección de portales",
    availabilityLabel: "Disponible",
    availableServicesTitle: "Servicios Disponibles",
    availableServicesDesc: "Explora y solicita servicios para tu comunidad",
    seeDetailsBtn: "Ver Detalles",
    requestBtn: "Solicitar",
    communityChatlabel: "Chat Comunitario",
    chatDescription: "Comunícate con tus vecinos y administrador de la comunidad",
    writeMessagePlaceholder: "Escribe tu mensaje...",
    scheduleVideoConference: "Programar Videoconferencia",
    communityVideoConferenceTitle: "Videoconferencia Comunitaria",
    scheduleVirtualMeetingsDesc: "Programa y participa en reuniones virtuales con tu comunidad",
    nextMeetingLabel: "Próxima Reunión",
    ordinaryAssemblyLabel: "Junta Ordinaria",
    meetingDate: "15 de Marzo, 2024 - 19:00",
    joinMeetingBtn: "Unirse a la Reunión",
    scheduleNewMeetingBtn: "Programar Nueva Reunión",
    reportIncidentTitle: "Reportar Incidencia",
    reportProblemsDesc: "Reporta problemas o incidencias en tu comunidad",
    incidentTypeLabel: "Tipo de Incidencia",
    maintenance: "Mantenimiento",
    cleaning: "Limpieza", 
    security: "Seguridad",
    other: "Otro",
    incidentDescriptionLabel: "Descripción de la Incidencia",
    describeDetailedProblemPlaceholder: "Describe el problema en detalle...",
    attachedImages: "Imágenes Adjuntas",
    attachPhotoBtn: "Adjuntar Foto",
    sendIncidentBtn: "Enviar Incidencia",
    recentIncidentsLabel: "Incidencias Recientes",
    garageDoorBrokenText: "Puerta del garaje rota",
    reportedAugust2Text: "Reportado el 2 de agosto",
    solvedLabel: "Solucionado",
    portalLightingText: "Iluminación del portal",
    reportedJuly28Text: "Reportado el 28 de julio",
    inProcessLabel: "En Proceso",
    communityContractsTitleLabel: "Contratos de la Comunidad",
    servicesContractedDesc: "Visualiza los servicios contratados por tu comunidad",
    activeLabel: "Activo",
    pendingLabel: "Pendiente",
    startDateLabel: "Fecha de Inicio",
    endDateLabel: "Fecha de Fin",
    valueLabel: "Valor",
    viewContractBtn: "Ver Contrato",
    downloadBtn: "Descargar",
    communityBudget2024Title: "Presupuesto Comunitario 2024",
    currentStateAnnualBudgetDesc: "Estado actual del presupuesto anual",
    totalBudgetLabel: "Presupuesto Total",
    spentLabel: "Gastado",
    availableLabel: "Disponible",
    breakdownByCategoriesTitle: "Desglose por Categorías",
    utilizedLabel: "utilizado",
    contactAdministratorTitleLabel: "Contactar Administrador",
    communicateDirectlyDesc: "Comunícate directamente con tu administrador de la comunidad",
    contactInformationLabel: "Información de Contacto",
    emailLabel2: "Correo Electrónico",
    phoneLabel2: "Teléfono",
    attentionScheduleLabel: "Horario de Atención",
    mondayToFridaySchedule: "Lunes a Viernes: 9:00 - 18:00",
    sendMessageBtn: "Enviar Mensaje",
    subjectLabel: "Asunto",
    messageSubjectPlaceholder: "Asunto del mensaje...",
    messageLabel: "Mensaje",
    writeMessageHerePlaceholder: "Iscribe tu mensaje aquí...",
    filterByStatus: "Filtrar por estado",
    allStatuses: "Todos los Estados",
    showingServices: "Mostrando",
    of: "de",
    services: "servicios",
    sortedBy: "Ordenado por",
    ascending: "ascendente",
    descending: "descendente",
    noServiceHistory: "Sin historial de servicios",
    clearFilters: "Limpiar filtros",
    findServices: "Encontrar Servicios",
    topRatedProviders: "Proveedores Mejor Valorados",
    basedOnCommunityRatings: "Basado en valoraciones de la comunidad",
    noRecommendations: "No hay recomendaciones disponibles",
    serviceRatingsTitleLabel: "Valoraciones de Servicios",
    yourRatingsCommunitServicesDesc: "Tus valoraciones para los servicios de la comunidad",
    configurationTitle: "Configuración",
    adjustPreferencesDesc: "Ajusta tus preferencias y configuraciones",
    notificationsLabel: "Notificaciones",
    emailNotificationsLabel: "Notificaciones por correo",
    emailNotificationsDesc: "Recibir notificaciones por correo electrónico",
    pushNotificationsLabel: "Notificaciones push",
    pushNotificationsDesc: "Recibir notificaciones push en tu dispositivo",
    meetingRemindersLabel: "Recordatorios de reuniones",
    videoconferenceAlertsLabel: "Alertas de videoconferencias",
    activateBtn: "Activar",
    privacyAndSecurityLabel: "Privacidad y Seguridad",
    changePasswordBtn: "Cambiar Contraseña",
    configureTwoFactorAuthBtn: "Configurar Autenticación de Dos Factores",
    downloadMyDataBtn: "Descargar Mis Datos",
    imagesOnly: "Solo se permiten imágenes"
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("es");

  const t = useCallback(
    (key: string, langOverride?: Language) => {
      const lang = langOverride || language;
      const keys = key.split(".");
      let result: any = translations[lang];
      for (const k of keys) {
        result = result?.[k];
        if (result === undefined) {
          // Fallback to English if translation is missing
          let fallbackResult: any = translations.en;
          for (const fk of keys) {
            fallbackResult = fallbackResult?.[fk];
          }
          return fallbackResult || key;
        }
      }
      return result || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
