import React, { createContext, useContext, useState, ReactNode, useCallback } from "react";

// Define the Language type
type Language = "es" | "en";

// Define the shape of the context
interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, langOverride?: Language) => string;
}

// Create the context with a default undefined value
export const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

// Define translations
const baseTranslations = {
  es: {
    // Common
    professionalServices: "Servicios profesionales",
    services: "Servicios",
    profile: "Perfil",
    signOut: "Cerrar sesión",
    languageEs: "Español",
    languageEn: "Inglés",
    hubit: "HUBIT",
    login: "Iniciar sesión",
    register: "Registrarse",
    welcomeBack: "Bienvenido de nuevo",
    loginToAccess: "Inicia sesión para acceder a tu cuenta",
    email: "Correo electrónico",
    enterEmail: "Introduce tu correo electrónico",
    password: "Contraseña",
    enterPassword: "Introduce tu contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    dontHaveAccount: "¿No tienes una cuenta?",
    createAccount: "Crear cuenta",
    registerToStart: "Regístrate para empezar a usar nuestros servicios",
    fullName: "Nombre completo",
    enterFullName: "Introduce tu nombre completo",
    createPassword: "Crea una contraseña",
    confirmPassword: "Confirmar contraseña",
    confirmYourPassword: "Confirma tu contraseña",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    
    // Home page
    homeTitle: "HUBIT - Hub de servicios comunitarios",
    homeDescription: "Hub de servicios comunitarios con pagos en criptomonedas",
    professionalServicesForHome: "Hub de servicios comunitarios",
    
    // Who We Are section
    whoWeAreTitle: "Quiénes Somos",
    whoWeAreIntro: "Somos una plataforma integral que conecta a administradores de fincas, empresas de servicios y vecinos para brindar transparencia en las necesidades de las comunidades de vecinos.",
    whoWeAreSummary: "Plataforma digital que conecta administradores de fincas, empresas de servicios y vecinos. Facilitamos la gestión transparente de comunidades mediante herramientas intuitivas, sistema de valoraciones verificadas y comunicación directa. Transformamos la administración tradicional en un ecosistema colaborativo donde todos se benefician: mejor gestión, servicios de calidad y comunidades más satisfechas.",
    ourMission: "Nuestra Misión",
    ourMissionText: "Nuestra misión es facilitar la comunicación, valoración y gestión de servicios, ayudando a las empresas a expandir su negocio mientras ofrecemos total transparencia a las comunidades.",
    ourEcosystem: "Nuestro Ecosistema",
    ourEcosystemText: "Creamos un ecosistema donde todos los participantes se benefician: los administradores pueden gestionar eficientemente las necesidades de sus comunidades, las empresas de servicios pueden mostrar su profesionalidad y obtener nuevos clientes, y los vecinos pueden valorar los servicios recibidos y tener voz en las decisiones comunitarias.",
    ourFundamentalValue: "Nuestro Valor Fundamental",
    ourFundamentalValueText: "La transparencia es nuestro valor fundamental, permitiendo que todas las partes involucradas tengan acceso a la información relevante, facilitando la toma de decisiones y mejorando la calidad de vida en las comunidades de vecinos.",
    
    // How It Works section
    howItWorksTitle: "Cómo Funciona",
    howItWorksIntro: "Nuestra plataforma funciona como un ecosistema integrado que conecta a los tres pilares fundamentales de las comunidades de vecinos:",
    forAdministrators: "Para Administradores",
    forAdministratorsText: "Ofrecemos herramientas digitales que simplifican la gestión diaria, permitiendo identificar necesidades, solicitar presupuestos y coordinar servicios desde un único panel de control intuitivo.",
    forServiceCompanies: "Para Empresas de Servicios",
    forServiceCompaniesText: "Proporcionamos un escaparate digital donde mostrar su profesionalidad, recibir solicitudes de presupuestos y obtener valoraciones verificadas que impulsan su reputación.",
    forNeighbors: "Para Vecinos",
    forNeighborsText: "Facilitamos una plataforma donde pueden reportar incidencias, seguir su resolución en tiempo real y valorar los servicios recibidos con total transparencia.",
    ratingsSystem: "Sistema de Valoraciones",
    ratingsSystemText: "Implementamos un sistema de evaluación que permite a los vecinos calificar los servicios, generando confianza y ayudando a tomar decisiones informadas.",
    virtuousCircle: "Esta integración crea un círculo virtuoso donde todos los participantes se benefician: mejores servicios para las comunidades, más oportunidades de negocio para los proveedores y una gestión más eficiente para los administradores.",
    
    // Our Achievements section
    ourAchievementsTitle: "Nuestros Logros",
    ourAchievementsIntro: "Desde el lanzamiento de nuestra plataforma, hemos logrado importantes avances que demuestran el impacto positivo de nuestro enfoque en la gestión de comunidades:",
    connectedCommunities: "Comunidades conectadas",
    connectedCommunitiesText: "Nuestra plataforma ya está siendo utilizada por cientos de comunidades de vecinos en todo el país.",
    verifiedCompanies: "Empresas verificadas",
    verifiedCompaniesText: "Contamos con una amplia red de proveedores de servicios de calidad que han pasado por nuestro proceso de verificación.",
    satisfactionIndex: "Índice de satisfacción",
    satisfactionIndexText: "Las valoraciones de los usuarios muestran un alto nivel de satisfacción con la plataforma y los servicios.",
    resolvedIncidents: "Incidencias resueltas",
    resolvedIncidentsText: "Hemos facilitado la resolución eficiente de miles de incidencias en comunidades, mejorando la calidad de vida.",
    achievementsConclusion: "Estos logros reflejan nuestro compromiso con la creación de un ecosistema transparente y eficiente que beneficia a todos los participantes: administradores, empresas de servicios y vecinos.",
    
    // Dashboard
    luxuryResidences: "Residencias de Lujo",
    luxuryResidencesDesc: "Comunidades de vecinos exclusivas",
    whoWeAre: "Quiénes Somos",
    howItWorks: "Cómo Funciona",
    achievements: "Nuestros Logros",
    communityMember: "Miembro de la Comunidad",
    serviceProvider: "Proveedor de Servicios",
    estateAdministrator: "Administrador de Fincas",
    particular: "Particular",
    
    // Dashboard content
    welcomeToDashboard: "Bienvenido al Panel de Control",
    selectUserType: "Selecciona tu tipo de usuario",
    selectUserTypeDesc: "Elige la opción que mejor describa tu perfil para acceder a las funcionalidades específicas",
    communityMemberDesc: "Accede a servicios exclusivos para tu comunidad",
    serviceProviderDesc: "Gestiona tus servicios y clientes",
    estateAdministratorDesc: "Administra propiedades y comunidades",
    particularDesc: "Servicios personalizados para particulares",
    accessDashboard: "Acceder al Panel",
    
    // Community Member
    communityDashboard: "Panel de Comunidad",
    availableServices: "Servicios Disponibles",
    requestService: "Solicitar Servicio",
    myRequests: "Mis Solicitudes",
    communityNews: "Noticias de la Comunidad",
    maintenance: "Mantenimiento",
    cleaning: "Limpieza",
    security: "Seguridad",
    gardening: "Jardinería",
    plumbing: "Fontanería",
    electrical: "Electricidad",
    painting: "Pintura",
    carpentry: "Carpintería",
    
    // Service Provider
    providerDashboard: "Panel de Proveedor",
    myServices: "Mis Servicios",
    serviceRequests: "Solicitudes de Servicio",
    earnings: "Ganancias",
    schedule: "Horario",
    clients: "Clientes",
    addService: "Añadir Servicio",
    manageServices: "Gestionar Servicios",
    
    // Estate Administrator
    adminDashboard: "Panel de Administrador",
    properties: "Propiedades",
    residents: "Residentes",
    serviceProviders: "Proveedores de Servicios",
    financialReports: "Informes Financieros",
    communications: "Comunicaciones",
    manageResidents: "Gestionar Residentes",
    
    // Particular
    particularDashboard: "Panel Particular",
    findServices: "Encontrar Servicios",
    myBookings: "Mis Reservas",
    favoriteProviders: "Proveedores Favoritos",
    serviceHistory: "Historial de Servicios",
    bookService: "Reservar Servicio",
    searchServices: "Buscar Servicios",
    
    // Common actions
    save: "Guardar",
    cancel: "Cancelar",
    edit: "Editar",
    delete: "Eliminar",
    view: "Ver",
    add: "Añadir",
    search: "Buscar",
    filter: "Filtrar",
    sort: "Ordenar",
    export: "Exportar",
    import: "Importar",
    refresh: "Actualizar",
    back: "Volver",
    next: "Siguiente",
    previous: "Anterior",
    submit: "Enviar",
    close: "Cerrar",
    open: "Abrir",
    
    // Status
    active: "Activo",
    inactive: "Inactivo",
    pending: "Pendiente",
    completed: "Completado",
    cancelled: "Cancelado",
    approved: "Aprobado",
    rejected: "Rechazado",
    
    // Navigation
    home: "Inicio",
    dashboard: "Panel",
    settings: "Configuración",
    help: "Ayuda",
    contact: "Contacto",
    about: "Acerca de",
    
    // Forms
    required: "Requerido",
    optional: "Opcional",
    pleaseSelect: "Por favor selecciona",
    selectOption: "Seleccionar opción",
    
    // Messages
    success: "Éxito",
    error: "Error",
    warning: "Advertencia",
    info: "Información",
    loading: "Cargando...",
    noData: "No hay datos disponibles",
    noResults: "No se encontraron resultados",
    
    // Service Provider Portal translations
    serviceProviderPortal: "Portal de Proveedor de Servicios",
    dashboardTitle: "Panel de Control",
    dashboardDesc: "Gestiona tus servicios y clientes",
    dashboardText: "Accede a tu panel de control para gestionar servicios, ver solicitudes y administrar tu perfil profesional.",
    openDashboard: "Abrir Panel de Control",
    serviceProfile: "Perfil de Servicios",
    manageOfferings: "Gestiona tus ofertas",
    serviceProfileText: "Configura y gestiona tu perfil de servicios para mostrar tu experiencia y especialidades.",
    popularCategories: "Categorías Populares",
    generalRepairs: "Reparaciones Generales",
    
    // Service Provider specific translations
    roofTiles: "Tejas y Techado",
    movingServices: "Servicios de Mudanza",
    locksmith: "Cerrajería",
    cableTV: "Televisión por Cable",
    packageDelivery: "Entrega de Paquetes",
    hairdressing: "Peluquería",
    catering: "Catering",
    activeBids: "Licitaciones Activas",
    bidManagement: "Gestión de Licitaciones",
    serviceCategories: "Categorías de Servicios",
    professionalProfile: "Perfil Profesional",
    businessHours: "Horario de Trabajo",
    serviceArea: "Área de Servicio",
    pricing: "Precios",
    portfolio: "Portafolio",
    certifications: "Certificaciones",
    workExperience: "Experiencia Laboral",
    specializations: "Especializaciones",
    equipment: "Equipamiento",
    availability: "Disponibilidad",
    emergencyServices: "Servicios de Emergencia",
    weekendAvailability: "Disponibilidad Fines de Semana",
    holidayServices: "Servicios en Festivos",
    
    // Service types and categories
    flooring: "Suelos",
    hvac: "Climatización",
    applianceRepair: "Reparación de Electrodomésticos",
    homeNetworking: "Redes Domésticas",
    restoration: "Restauración",
    deepCleaning: "Limpieza Profunda",
    interiorDecoration: "Decoración Interior",
    completeRenovation: "Renovación Completa",
    landscaping: "Paisajismo",
    
    // Service provider dashboard translations
    serviceProviderDashboard: "Panel de Proveedor de Servicios",
    serviceOverview: "Resumen de Servicios",
    bids: "Licitaciones",
    communityRequests: "Solicitudes de la Comunidad",
    requests: "Solicitudes",
    editBid: "Editar Licitación",
    contactClient: "Contactar Cliente",
    submitBid: "Enviar Licitación",
    noRequests: "No hay solicitudes disponibles",
    browseAllRequests: "Explorar Todas las Solicitudes",
    overview: "Resumen",
    
    // Profile and company information translations
    companyInformation: "Información de la Empresa",
    companyName: "Nombre de la Empresa",
    taxId: "NIF/CIF",
    businessAddress: "Dirección Comercial",
    website: "Sitio Web",
    companyDescription: "Descripción de la Empresa",
    saveChanges: "Guardar Cambios",
    servicesOffered: "Servicios Ofrecidos",
    editServices: "Editar Servicios",
    waterHeating: "Calefacción de Agua",
    emergencyService: "Servicio de Emergencia",
    certificationsLicenses: "Certificaciones y Licencias",
    addCertification: "Agregar Certificación",
    professionalLicense: "Licencia Profesional",
    validUntil: "Válido hasta",
    verified: "Verificado",
    insuranceCertificate: "Certificado de Seguro",
    coverage: "Cobertura",
    qualityCertification: "Certificación de Calidad",
    addPhoto: "Agregar Foto",
    change: "Cambiar",
    details: "Detalles",
    uploadPhoto: "Subir Foto",
    recentReviews: "Reseñas Recientes",
    viewAllReviews: "Ver Todas las Reseñas",
    weekAgo: "semana atrás",
    quickStats: "Estadísticas Rápidas",
    completedJobs: "Trabajos Completados",
    responseTime: "Tiempo de Respuesta",
    memberSince: "Miembro desde",
    viewPublicProfile: "Ver Perfil Público",
    
    // Dashboard overview translations
    vsLastWeek: "vs semana pasada",
    thisMonth: "este mes",
    averageRating: "Calificación Promedio",
    basedOn: "basado en",
    upcomingAppointments: "Próximas Citas",
    noUpcomingAppointments: "No hay citas próximas",
    
    // Bid and request translations
    currentBidsFor: "Licitaciones Actuales para",
    communityRequestsFor: "Solicitudes de la Comunidad para",
    noBidsInCategory: "No hay licitaciones en esta categoría",
    noRequestsInCategory: "No hay solicitudes en esta categoría",
    budget: "Presupuesto",
    
    // All service translations
    bathroomPlumbingOverhaul: "Renovación Completa de Fontanería de Baño",
    kitchenSinkInstallation: "Instalación de Fregadero de Cocina",
    toiletRepair: "Reparación de Inodoro",
    leakDetection: "Detección de Fugas",
    fullHousePlumbing: "Fontanería de Casa Completa",
    showerInstallation: "Instalación de Ducha",
    drainCleaning: "Limpieza de Desagües",
    waterHeaterReplacement: "Reemplazo de Calentador de Agua",
    faucetReplacement: "Reemplazo de Grifo",
    sewerLineRepair: "Reparación de Línea de Alcantarillado",
    
    // Company names
    elitePlumbingSolutions: "Soluciones de Fontanería Elite",
    waterworksPro: "Fontanería Pro",
    reliableHomeServices: "Servicios Domésticos Confiables",
    precisionPlumbers: "Fontaneros de Precisión",
    masterPlumbingCo: "Compañía Maestros de Fontanería",
    qualityPlumbing: "Fontanería de Calidad",
    drainMasters: "Maestros de Desagües",
    hotWaterExperts: "Expertos en Agua Caliente",
    fixItPlumbing: "Fontanería Arréglalo",
    deepDrainServices: "Servicios de Desagües Profundos",
    
    // Electrical translations
    homeRewiring: "Recableado de Casa",
    outletInstallation: "Instalación de Enchufes",
    lightingInstallation: "Instalación de Iluminación",
    panelUpgrade: "Actualización de Panel",
    ceilingFanInstallation: "Instalación de Ventilador de Techo",
    electricalInspection: "Inspección Eléctrica",
    generatorInstallation: "Instalación de Generador",
    switchReplacement: "Reemplazo de Interruptores",
    smartHomeWiring: "Cableado de Casa Inteligente",
    outdoorLighting: "Iluminación Exterior",
    
    // Electrical companies
    powerElectrical: "Eléctrica Power",
    voltExperts: "Expertos en Voltaje",
    brightSolutions: "Soluciones Brillantes",
    circuitPros: "Profesionales de Circuitos",
    fanMasters: "Maestros de Ventiladores",
    safetyFirst: "Seguridad Primero",
    powerBackup: "Respaldo de Energía",
    switchItUp: "Cambia el Interruptor",
    smartElectric: "Eléctrica Inteligente",
    nightLightPros: "Profesionales de Luz Nocturna",
    
    // Additional translations for all categories
    masonry: "Albañilería",
    roofing: "Techado",
    myProfile: "Mi Perfil",
    reviews: "reseñas",
    viewDetails: "Ver Detalles",
    phoneLabel: "Teléfono",
    emailLabel: "Correo Electrónico",
    daysAgo: "días atrás",
    editProfile: "Editar Perfil",
    
    // All other service categories and companies
    interiorPainting: "Pintura Interior",
    exteriorPainting: "Pintura Exterior",
    accentWall: "Pared de Acento",
    cabinetRefinishing: "Refinado de Gabinetes",
    deckStaining: "Tinción de Terraza",
    wallpaperRemoval: "Remoción de Papel Tapiz",
    textureApplication: "Aplicación de Textura",
    commercialPainting: "Pintura Comercial",
    trimPainting: "Pintura de Molduras",
    fenceStaining: "Tinción de Cerca",
    
    colorMasters: "Maestros del Color",
    freshCoatPros: "Profesionales de Capa Fresca",
    accentArtistry: "Arte de Acentos",
    cabinetRenew: "Renovación de Gabinetes",
    deckRevival: "Renovación de Terraza",
    smoothWalls: "Paredes Lisas",
    textureArtists: "Artistas de Textura",
    proPainters: "Pintores Profesionales",
    detailPainters: "Pintores de Detalle",
    fenceRefresh: "Renovación de Cercas",
    
    // Continue with all other service categories...
    hardwoodInstallation: "Instalación de Madera Dura",
    tileFlorInstallation: "Instalación de Suelo de Azulejos",
    carpetInstallation: "Instalación de Alfombra",
    vinylInstallation: "Instalación de Vinilo",
    floorRefinishing: "Refinado de Suelos",
    laminateInstallation: "Instalación de Laminado",
    floorRepair: "Reparación de Suelos",
    marbleInstallation: "Instalación de Mármol",
    subfloorRepair: "Reparación de Subsuelo",
    radiantFloorHeating: "Calefacción Radiante de Suelo",
    
    hardwoodHeroes: "Héroes de Madera Dura",
    tileExperts: "Expertos en Azulejos",
    carpetKings: "Reyes de Alfombras",
    vinylPros: "Profesionales de Vinilo",
    floorRevival: "Renovación de Suelos",
    laminateLords: "Señores del Laminado",
    repairRight: "Reparación Correcta",
    marbleMasters: "Maestros del Mármol",
    foundationFix: "Arreglo de Cimientos",
    warmWalkers: "Caminantes Cálidos",
    
    completeRoofReplacement: "Reemplazo Completo de Techo",
    roofRepair: "Reparación de Techo",
    gutterInstallation: "Instalación de Canalones",
    chimneyRepair: "Reparación de Chimenea",
    
    // Add all remaining translations to complete the Spanish version
    topRoofing: "Techado Superior",
    leakStoppers: "Detener Fugas",
    gutterGuards: "Protectores de Canalones",
    chimneyChamps: "Campeones de Chimeneas",
    ventInstallation: "Instalación de Ventilación",
    ventilationPros: "Profesionales de Ventilación",
    metalRoofInstallation: "Instalación de Techo Metálico",
    metalMasters: "Maestros del Metal",
    skylightInstallation: "Instalación de Tragaluz",
    skyBrights: "Luces del Cielo",
    flatRoofCoating: "Revestimiento de Techo Plano",
    flatRoofExperts: "Expertos en Techos Planos",
    solarRoofInstallation: "Instalación de Techo Solar",
    solarRoofing: "Techado Solar",
    roofInspection: "Inspección de Techo",
    roofInspectors: "Inspectores de Techos",
    
    // HVAC translations
    acInstallation: "Instalación de Aire Acondicionado",
    coolAirPros: "Profesionales de Aire Fresco",
    furnaceInstallation: "Instalación de Caldera",
    heatMasters: "Maestros del Calor",
    hvacMaintenance: "Mantenimiento de HVAC",
    systemService: "Servicio de Sistemas",
    ductCleaning: "Limpieza de Conductos",
    freshAirD