import React, { createContext, useContext, useState, ReactNode, useCallback } from "react";

type Language = "es" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, langOverride?: Language) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // General & Navigation
    professionalServices: "Professional Services Hub",
    services: "Services",
    profile: "Profile",
    signOut: "Sign Out",
    languageEs: "Spanish",
    languageEn: "English",
    hubit: "HuBiT",
    login: "Login",
    register: "Register",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    view: "View",
    add: "Add",
    search: "Search",
    filter: "Filter",
    sort: "Sort",
    export: "Export",
    import: "Import",
    refresh: "Refresh",
    back: "Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    close: "Close",
    open: "Open",
    home: "Home",
    dashboard: "Dashboard",
    settings: "Settings",
    help: "Help",
    contact: "Contact",
    about: "About",
    
    // Status & Notifications
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
    approved: "Approved",
    rejected: "Rejected",
    success: "Success",
    error: "Error",
    warning: "Warning",
    info: "Information",
    loading: "Loading...",
    noData: "No data available",
    noResults: "No results found",
    urgent: "Urgent",
    normal: "Normal",
    low: "Low",
    medium: "Medium",
    high: "High",
    critical: "Critical",
    resolved: "Resolved",
    inProgress: "In Progress",
    closed: "Closed",
    residents: "Residents",

    // Forms
    required: "Required",
    optional: "Optional",
    pleaseSelect: "Please select",
    selectOption: "Select option",
    email: "Email",
    enterEmail: "Enter your email",
    password: "Password",
    enterPassword: "Enter your password",
    confirmPassword: "Confirm Password",
    confirmYourPassword: "Confirm your password",
    fullName: "Full Name",
    enterFullName: "Enter your full name",

    // Auth
    welcomeBack: "Welcome Back",
    loginToAccess: "Log in to access your account",
    forgotPassword: "Forgot your password?",
    dontHaveAccount: "Don't have an account?",
    createAccount: "Create Account",
    registerToStart: "Register to start using our services",
    createPassword: "Create a password",
    alreadyHaveAccount: "Already have an account?",
    
    // Home Page & General Content
    homeTitle: "HuBiT - Community Services Hub",
    homeDescription: "Community services hub with cryptocurrency payments",
    professionalServicesForHome: "Community Services Hub",
    whoWeAreTitle: "Who We Are",
    whoWeAreIntro: "We are a comprehensive platform that connects property managers, service companies, and neighbors to provide transparency in the needs of neighborhood communities.",
    whoWeAreSummary: "A digital platform connecting property managers, service companies, and neighbors. We facilitate transparent community management through intuitive tools, a verified rating system, and direct communication. We transform traditional management into a collaborative ecosystem where everyone benefits: better management, quality services, and more satisfied communities.",
    ourMission: "Our Mission",
    ourMissionText: "Our mission is to facilitate communication, valuation, and management of services, helping companies expand their business while offering full transparency to communities.",
    ourEcosystem: "Our Ecosystem",
    ourEcosystemText: "We create an ecosystem where all participants benefit: administrators can efficiently manage their communities' needs, service companies can showcase their professionalism and gain new clients, and neighbors can rate the services received and have a voice in community decisions.",
    ourFundamentalValue: "Our Fundamental Value",
    ourFundamentalValueText: "Transparency is our fundamental value, allowing all parties involved to have access to relevant information, facilitating decision-making, and improving the quality of life in neighborhood communities.",
    howItWorksTitle: "How It Works",
    howItWorksIntro: "Our platform functions as an integrated ecosystem that connects the three fundamental pillars of neighborhood communities:",
    forAdministrators: "For Administrators",
    forAdministratorsText: "We offer digital tools that simplify daily management, allowing them to identify needs, request quotes, and coordinate services from a single intuitive control panel.",
    forServiceCompanies: "For Service Companies",
    forServiceCompaniesText: "We provide a digital showcase to display their professionalism, receive quote requests, and obtain verified ratings that boost their reputation.",
    forNeighbors: "For Neighbors",
    forNeighborsText: "We provide a platform where they can report incidents, track their resolution in real-time, and rate the services received with full transparency.",
    ratingsSystem: "Rating System",
    ratingsSystemText: "We implement an evaluation system that allows neighbors to rate services, building trust and helping to make informed decisions.",
    virtuousCircle: "This integration creates a virtuous circle where all participants benefit: better services for communities, more business opportunities for providers, and more efficient management for administrators.",
    ourAchievementsTitle: "Our Achievements",
    ourAchievementsIntro: "Since the launch of our platform, we have made significant progress that demonstrates the positive impact of our approach to community management:",
    connectedCommunities: "Connected Communities",
    connectedCommunitiesText: "Our platform is already being used by hundreds of neighborhood communities across the country.",
    verifiedCompanies: "Verified Companies",
    verifiedCompaniesText: "We have a wide network of quality service providers who have gone through our verification process.",
    satisfactionIndex: "Satisfaction Index",
    satisfactionIndexText: "User ratings show a high level of satisfaction with the platform and services.",
    resolvedIncidents: "Incidents Resolved",
    resolvedIncidentsText: "We have facilitated the efficient resolution of thousands of incidents in communities, improving the quality of life.",
    achievementsConclusion: "These achievements reflect our commitment to creating a transparent and efficient ecosystem that benefits all participants: administrators, service companies, and neighbors.",
    luxuryResidences: "Luxury Residences",
    luxuryResidencesDesc: "Exclusive neighborhood communities",
    whoWeAre: "Who We Are",
    howItWorks: "How It Works",
    achievements: "Our Achievements",
    features: "Features",

    // User Roles & Dashboards
    communityMember: "Community Member",
    serviceProvider: "Service Provider",
    estateAdministrator: "Estate Administrator",
    particular: "Individual",
    welcomeToDashboard: "Welcome to the Dashboard",
    selectUserType: "Select your user type",
    selectUserTypeDesc: "Choose the option that best describes your profile to access specific functionalities",
    whatsYourRole: "What's your role?",
    communityMemberDesc: "Access exclusive services for your community",
    serviceProviderDesc: "Manage your services and clients",
    estateAdministratorDesc: "Manage properties and communities",
    particularDesc: "Personalized services for individuals",
    accessDashboard: "Access Dashboard",
    communityDashboard: "Community Dashboard",
    providerDashboard: "Provider Dashboard",
    adminDashboard: "Administrator Dashboard",
    particularDashboard: "Individual Dashboard",
    controlPanel: "Control Panel",

    // Services
    plumbing: "Plumbing",
    electrical: "Electrical",
    painting: "Painting",
    carpentry: "Carpentry",
    maintenance: "Maintenance",
    cleaning: "Cleaning",
    security: "Security",
    gardening: "Gardening",
    masonry: "Masonry",
    roofing: "Roofing",
    generalRepairs: "General Repairs",
    roofTiles: "Roof Tiles",
    movingServices: "Moving Services",
    locksmith: "Locksmith",
    cableTV: "Cable TV",
    packageDelivery: "Package Delivery",
    hairdressing: "Hairdressing",
    catering: "Catering",
    flooring: "Flooring",
    hvac: "HVAC",
    applianceRepair: "Appliance Repair",
    homeNetworking: "Home Networking",
    restoration: "Restoration",
    deepCleaning: "Deep Cleaning",
    interiorDecoration: "Interior Decoration",
    completeRenovation: "Complete Renovation",
    landscaping: "Landscaping",
    waterHeating: "Water Heating",
    emergencyService: "Emergency Service",
    other: "Other",

    // Service Provider Specific
    serviceProviderPortal: "Service Provider Portal",
    dashboardTitle: "Dashboard",
    dashboardDesc: "Manage your services and clients",
    dashboardText: "Access your dashboard to manage services, view requests, and manage your professional profile.",
    openDashboard: "Open Dashboard",
    serviceProfile: "Service Profile",
    manageOfferings: "Manage your offerings",
    serviceProfileText: "Set up and manage your service profile to showcase your experience and specialties.",
    popularCategories: "Popular Categories",
    activeBids: "Active Bids",
    bidManagement: "Bid Management",
    serviceCategories: "Service Categories",
    professionalProfile: "Professional Profile",
    businessHours: "Business Hours",
    serviceArea: "Service Area",
    pricing: "Pricing",
    portfolio: "Portfolio",
    certifications: "Certifications",
    workExperience: "Work Experience",
    specializations: "Specializations",
    equipment: "Equipment",
    availability: "Availability",
    emergencyServices: "Emergency Services",
    weekendAvailability: "Weekend Availability",
    holidayServices: "Holiday Services",
    serviceOverview: "Service Overview",
    bids: "Bids",
    communityRequests: "Community Requests",
    requests: "Requests",
    editBid: "Edit Bid",
    contactClient: "Contact Client",
    submitBid: "Submit Bid",
    noRequests: "No requests available",
    browseAllRequests: "Browse All Requests",
    overview: "Overview",
    companyInformation: "Company Information",
    companyName: "Company Name",
    taxId: "Tax ID",
    businessAddress: "Business Address",
    website: "Website",
    companyDescription: "Company Description",
    saveChanges: "Save Changes",
    servicesOffered: "Services Offered",
    editServices: "Edit Services",
    certificationsLicenses: "Certifications & Licenses",
    addCertification: "Add Certification",
    professionalLicense: "Professional License",
    validUntil: "Valid until",
    verified: "Verified",
    insuranceCertificate: "Insurance Certificate",
    coverage: "Coverage",
    qualityCertification: "Quality Certification",
    addPhoto: "Add Photo",
    change: "Change",
    details: "Details",
    uploadPhoto: "Upload Photo",
    recentReviews: "Recent Reviews",
    viewAllReviews: "View All Reviews",
    weekAgo: "week ago",
    daysAgo: "days ago",
    quickStats: "Quick Stats",
    completedJobs: "Completed Jobs",
    responseTime: "Response Time",
    memberSince: "Member Since",
    viewPublicProfile: "View Public Profile",
    vsLastWeek: "vs last week",
    thisMonth: "this month",
    reviews: "reviews",
    upcomingAppointments: "Upcoming Appointments",
    noUpcomingAppointments: "No upcoming appointments",
    currentBidsFor: "Current Bids for",
    communityRequestsFor: "Community Requests for",
    noBidsInCategory: "No bids in this category",
    noRequestsInCategory: "No requests in this category",
    budget: "Budget",

    // Particular Dashboard
    myProfile: "My Profile",
    personalInformation: "Personal Information",
    fullNameLabel: "Full Name",
    emailLabel: "Email",
    phoneLabel: "Phone",
    locationLabel: "Location",
    editProfile: "Edit Profile",
    individual: "Individual",
    requestQuote: "Request Quote",
    serviceType: "Service Type",
    selectServiceType: "Select service type",
    preferredDate: "Preferred Date",
    serviceTitle: "Service Title",
    exampleLeakRepair: "e.g. Bathroom leak repair",
    detailedDescription: "Detailed Description",
    describeServiceNeeded: "Describe the service you need",
    requestQuotes: "Request Quotes",
    searchProviders: "Search Providers",
    viewProfile: "View Profile",
    request: "Request",
    loadMoreProviders: "Load More Providers",
    myFavorites: "My Favorites",
    noFavoriteProviders: "You have no favorite providers",
    addFavoriteProvidersDesc: "Add providers to your favorites for quick access",
    exploreProviders: "Explore Providers",
    myProperties: "My Properties",
    addProperty: "Add Property",
    editProperty: "Edit Property",
    deleteProperty: "Delete Property",
    propertyType: "Property Type",
    propertyAddress: "Property Address",
    city: "City",
    postalCode: "Postal Code",
    propertySize: "Property Size",
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    yearBuilt: "Year Built",
    propertyDescription: "Property Description",
    propertyStatus: "Property Status",
    owned: "Owned",
    rented: "Rented",
    vacant: "Vacant",
    apartment: "Apartment",
    house: "House",
    townhouse: "Townhouse",
    condo: "Condo",
    studio: "Studio",
    selectProperty: "Select Property",
    noPropertiesFound: "No properties found",
    addFirstProperty: "Add your first property",
    propertyManager: "Property Manager",
    apartmentInCenter: "Downtown Apartment",
    beachHouse: "Beach House",
    manage: "Manage",
    notifications: "Notifications",
    quoteReceived: "Quote Received",
    quoteReceivedDesc: "You have received a new quote for your request",
    hoursAgo: "2 hours ago",
    viewQuote: "View Quote",
    serviceCompleted: "Service Completed",
    serviceCompletedDesc: "The plumbing service has been completed",
    yesterday: "yesterday",
    rateService: "Rate Service",
    viewAllNotifications: "View All Notifications",
    configuration: "Configuration",
    accountPreferences: "Account Preferences",
    language: "Language",
    spanish: "Spanish",
    english: "English",
    catalan: "Catalan",
    emailNotifications: "Email Notifications",
    pushNotifications: "Push Notifications",
    smsNotifications: "SMS Notifications",
    privacy: "Privacy",
    profileVisibleToProviders: "Profile visible to providers",
    shareServiceHistory: "Share service history",
    changePassword: "Change Password",
    setupTwoFactor: "Setup Two-Factor Authentication",
    manageConnectedDevices: "Manage Connected Devices",
    dataAndPrivacy: "Data and Privacy",
    downloadMyData: "Download My Data",
    deleteMyAccount: "Delete My Account",
    myPayments: "My Payments",
    noPaymentHistory: "No payment history available",
    recommendations: "Recommendations",
    noRecommendations: "No recommendations available",
    myAwards: "My Awards",
    noAwards: "No awards available",
    unit: "Unit",
    noPropertySelected: "No property selected",
    propertySelected: "Property selected",
    selectAPropertyToManage: "Select a property to manage",
    changeProperty: "Change Property",
    noServiceHistoryMessage: "You have not used any service yet",

    // Financial
    paymentSystemTitle: "Hybrid Payment System",
    paymentSystemIntro: "We offer multiple payment options to adapt to all our users' preferences",
    fiatCurrencies: "FIAT Currencies",
    fiatDescription: "Traditional and secure payment methods",
    cryptocurrencies: "Cryptocurrencies",
    cryptoDescription: "Decentralized payments with major cryptocurrencies",
    bitcoin: "Bitcoin (BTC)",
    ethereum: "Ethereum (ETH)",
    binanceCoin: "Binance Coin (BNB)",
    solana: "Solana (SOL)",
    hubitToken: "HUBIT Token",
    hbitDescription: "Our native token with exclusive benefits",
    acceptedPayments: "Accepted Payment Types",
    p2pPayments: "Person to Person",
    p2bPayments: "Person to Business",
    b2pPayments: "Business to Person",
    b2bPayments: "Business to Business",
    howToBuyHbitTitle: "How to Buy HBIT",
    howToBuyHbitIntro: "Follow these simple steps to acquire HBIT tokens and access exclusive benefits",
    hbitBenefits: "Benefits of using HBIT",
    benefit1: "Exclusive Discounts",
    benefit2: "Fast Transactions",
    benefit3: "Loyalty Rewards",
    benefit4: "Priority Access",
    startUsingHbit: "Start using HBIT",
    learnMore: "Learn more",

    // Community & Particular Member Dashboards (Shared)
    serviceHistory: "Service History",
    rateThisService: "Rate This Service",
    serviceRating: "Service Rating",
    overallSatisfaction: "Overall Satisfaction",
    serviceQuality: "Service Quality",
    timeliness: "Timeliness",
    professionalism: "Professionalism",
    valueForMoney: "Value for Money",
    wouldRecommend: "Would Recommend",
    addComment: "Add Comment",
    commentPlaceholder: "Share your experience with this service...",
    submitRating: "Submit Rating",
    editRating: "Edit Rating",
    deleteRating: "Delete Rating",
    ratingSubmitted: "Rating Submitted",
    thankYouForRating: "Thank You for Rating",
    noServicesToRate: "You have no services to rate",
    noServiceHistory: "You have no service history",
    completedServices: "Completed Services",
    pendingServices: "Pending Services",
    cancelledServices: "Cancelled Services",
    filterByStatus: "Filter by Status",
    filterByCategory: "Filter by Category",
    sortByDate: "Sort by Date",
    sortByRating: "Sort by Rating",
    mostRecent: "Most Recent",
    oldest: "Oldest",
    highestRated: "Highest Rated",
    lowestRated: "Lowest Rated",
    allCategories: "All Categories",
    allStatuses: "All Statuses",
    serviceDate: "Service Date",
    serviceCost: "Service Cost",
    providerName: "Provider Name",
    yourRating: "Your Rating",
    notRated: "Not Rated",
    rateNow: "Rate Now",
    viewDetails: "View Details",
    contactProvider: "Contact Provider",
    repeatService: "Repeat Service",
    reportIssue: "Report Issue",
    serviceDetails: "Service Details",
    serviceId: "Service ID",
    scheduledFor: "Scheduled For",
    actualDate: "Actual Date",
    duration: "Duration",
    materials: "Materials",
    laborCost: "Labor Cost",
    totalCost: "Total Cost",
    paymentMethod: "Payment Method",
    invoiceNumber: "Invoice Number",
    warranty: "Warranty",
    followUpRequired: "Follow Up Required",
    serviceNotes: "Service Notes",
    beforePhotos: "Before Photos",
    afterPhotos: "After Photos",
    topRatedProviders: "Top Rated Providers",
    recommendedForYou: "Recommended for You",
    basedOnHistory: "Based on your history",
    basedOnCommunityRatings: "Based on your community's ratings",
    similarServices: "Similar Services",
    recentlyUsed: "Recently Used",
    popularInYourArea: "Popular in Your Area",
    newProviders: "New Providers",
    specialOffers: "Special Offers",
    premiumProviders: "Premium Providers",
    emergencyAvailable: "Emergency Available",
    weekendService: "Weekend Service",
    sameDay: "Same Day",
    guaranteedService: "Guaranteed Service",
    ratings: "Ratings",
    totalRatings: "Total Ratings",
    averageRating: "Average Rating",
    ratingBreakdown: "Rating Breakdown",
    fiveStars: "Five Stars",
    fourStars: "Four Stars",
    threeStars: "Three Stars",
    twoStars: "Two Stars",
    oneStar: "One Star",
    mostHelpfulReviews: "Most Helpful Reviews",
    verifiedCustomer: "Verified Customer",
    helpfulReview: "Helpful Review",
    reportReview: "Report Review",
    sortReviews: "Sort Reviews",
    newestFirst: "Newest First",
    oldestFirst: "Oldest First",
    highestRatedFirst: "Highest Rated First",
    lowestRatedFirst: "Lowest Rated First",
    yes: "Yes",
    no: "No",
    "Muy Insatisfecho": "Very Unsatisfied",
    "Insatisfecho": "Unsatisfied",
    "Neutral": "Neutral",
    "Satisfecho": "Satisfied",
    "Muy Satisfecho": "Very Satisfied",
    "Selecciona una puntuación": "Select a rating",
    jobs: "jobs",
    properties: "Properties",

    // Community Member Dashboard Specific
    availableServices: "Available Services",
    requestService: "Request Service",
    myRequests: "My Requests",
    communityNews: "Community News",
    myServices: "My Services",
    serviceRequests: "Service Requests",
    earnings: "Earnings",
    schedule: "Schedule",
    clients: "Clients",
    addService: "Add Service",
    manageServices: "Manage Services",
    financialReports: "Financial Reports",
    communications: "Communications",
    manageResidents: "Manage Residents",
    findServices: "Find Services",
    myBookings: "My Bookings",
    favoriteProviders: "Favorite Providers",
    bookService: "Book Service",
    searchServices: "Search Services",
    communityMemberDashboard: "Community Member Dashboard",
    communityChat: "Community Chat",
    scheduleVideoConference: "Schedule Video Conference",
    informIssue: "Report Issue",
    communityContracts: "Community Contracts",
    communityBudget: "Community Budget",
    contactAdministrator: "Contact Administrator",
    serviceRatings: "Service Ratings",
    elevatorMaintenance: "Elevator Maintenance",
    gatesCleaning: "Gates Cleaning",
    commonAreasGardening: "Common Areas Gardening",
    lightingRepair: "Lighting Repair",
    excellentCommunityServiceComment: "Excellent service for the entire community",
    goodWorkStairsComment: "Good overall work, could improve on stairs",
    preventiveMaintenance: "Preventive Maintenance",
    urgentRepairs: "Urgent Repairs",
    modernization: "Modernization",
    landscapeDesign: "Landscape Design",
    irrigationSystems: "Irrigation Systems",
    gatesDisinfection: "Gate Disinfection",
    maintenanceSpec: "Maintenance",

    // Property Selection
    communityMemberProperties: "Community Member Properties",
    particularProperties: "Individual Properties",
    selectPropertyDescription: "Select one of your properties to manage it.",
    selectPropertyToAccess: "Select the property you want to access to manage all related services and information.",
    searchProperties: "Search by name or address...",
    noPropertiesFoundDescription: "It seems you haven't added any properties yet.",

    // Whitepaper
    whitepaperTitle: "Whitepaper de HuBiT",
    whitepaperSubtitle: "Gestión Descentralizada de Propiedades en Solana",
    executiveSummary: "Resumen Ejecutivo",
    executiveSummaryText: "HuBiT es un token de utilidad desarrollado en Solana que conecta administradores de propiedades, proveedores de servicios y residentes en un ecosistema transparente. Al poseer HuBiT, los usuarios acceden a funciones premium, mientras que el token financia el crecimiento de la plataforma sin intermediarios.",
    whySolana: "¿Por qué Solana?",
    lowFees: "Comisiones bajas por transacción",
    highSpeed: "Alta velocidad TPS",
    massAdoption: "Preparado para adopción masiva",
    tokenomics: "Economía del Token",
    tokenDetails: "Detalles del Token",
    tokenName: "Nombre:",
    blockchain: "Blockchain:",
    totalSupply: "Suministro Total:",
    contract: "Contrato:",
    toBeDeployed: "[Pendiente de despliegue]",
    distribution: "Distribución",
    teamAdvisors: "Equipo y Asesores",
    communityRewards: "Comunidad y Recompensas",
    ecosystemFund: "Fondo del Ecosistema",
    publicCirculation: "Circulación Pública",
    utility: "Utilidad",
    holdHubit: "Poseer 100 HuBiT:",
    holdHubitDesc: "Aplicación sin anuncios, derechos de voto, funciones premium",
    payAsYouGo: "Pago por uso:",
    payAsYouGoDesc: "€1.99/mes para usuarios sin tokens",
    staking: "Staking:",
    stakingDesc: "Obtén recompensas por bloquear tokens (fase futura)",
    roadmap: "Hoja de Ruta",
    q3Title: "T3 2025",
    mvpDevelopment: "Desarrollo del MVP:",
    mvpDevelopmentDesc: "Demostración de la aplicación HuBiT",
    brandLaunch: "Lanzamiento de la Marca:",
    brandLaunchDesc: "Sitio web + Twitter",
    tokenDeployment: "Lanzamiento del Token:",
    tokenDeploymentDesc: "Creación del token SPL en Solana",
    q4Title: "T4 2025",
    appBetaRelease: "Lanzamiento Beta de la App:",
    appBetaReleaseDesc: "iOS/Android (funciones de gestión de propiedades, integración con billetera Solana)",
    listings: "Cotizaciones:",
    listingsDesc: "CoinMarketCap, CoinGecko, exchanges centralizados y descentralizados",
    partnerships: "Alianzas Estratégicas:",
    partnershipsDesc: "Incorporación de más de 50 proveedores de servicios",
    q1Title: "T1 2026",
    globalExpansion: "Expansión Global:",
    globalExpansionDesc: "Campañas de marketing internacional",
    tenThousandUsers: "Más de 10,000 Usuarios:",
    tenThousandUsersDesc: "Incentivados mediante airdrops y recompensas comunitarias",
    governanceDao: "DAO de Gobernanza:",
    governanceDaoDesc: "Los poseedores de tokens participan en las decisiones sobre mejoras de la plataforma",
    joinCommunity: "Únete a nuestra comunidad y forma parte del futuro de la gestión inmobiliaria",
    followTwitter: "Síguenos en Twitter",
  },
  es: {
    // General & Navigation
    professionalServices: "Professional Services Hub",
    services: "Servicios",
    profile: "Perfil",
    signOut: "Cerrar sesión",
    languageEs: "Español",
    languageEn: "Inglés",
    hubit: "HuBiT",
    login: "Iniciar sesión",
    register: "Registrarse",
    save: "Guardar",
    cancel: "Cancelar",
    edit: "Editar",
    delete: "Eliminar",
    view: "Ver",
    add: "Añadir",
    search: "Buscar",
    filter: "Filtrar",
    sort: "Ordenar",
    export: "Exportar",
    import: "Importar",
    refresh: "Actualizar",
    back: "Volver",
    next: "Siguiente",
    previous: "Anterior",
    submit: "Enviar",
    close: "Cerrar",
    open: "Abrir",
    home: "Inicio",
    dashboard: "Panel de Control",
    settings: "Configuración",
    help: "Ayuda",
    contact: "Contacto",
    about: "Acerca de",
    
    // Status & Notifications
    active: "Activo",
    inactive: "Inactivo",
    pending: "Pendiente",
    completed: "Completado",
    cancelled: "Cancelado",
    approved: "Aprobado",
    rejected: "Rechazado",
    success: "Éxito",
    error: "Error",
    warning: "Advertencia",
    info: "Información",
    loading: "Cargando...",
    noData: "No hay datos disponibles",
    noResults: "No se encontraron resultados",
    urgent: "Urgente",
    normal: "Normal",
    low: "Baja",
    medium: "Medio",
    high: "Alto",
    critical: "Crítico",
    resolved: "Resueltas",
    inProgress: "En Progreso",
    closed: "Cerradas",
    residents: "Residentes",

    // Forms
    required: "Requerido",
    optional: "Opcional",
    pleaseSelect: "Por favor selecciona",
    selectOption: "Seleccionar opción",
    email: "Correo electrónico",
    enterEmail: "Introduce tu correo electrónico",
    password: "Contraseña",
    enterPassword: "Introduce tu contraseña",
    confirmPassword: "Confirmar contraseña",
    confirmYourPassword: "Confirma tu contraseña",
    fullName: "Nombre completo",
    enterFullName: "Introduce tu nombre completo",

    // Auth
    welcomeBack: "Bienvenido de nuevo",
    loginToAccess: "Inicia sesión para acceder a tu cuenta",
    forgotPassword: "¿Olvidaste tu contraseña?",
    dontHaveAccount: "¿No tienes una cuenta?",
    createAccount: "Crear cuenta",
    registerToStart: "Regístrate para empezar a usar nuestros servicios",
    createPassword: "Crea una contraseña",
    alreadyHaveAccount: "¿Ya tienes una cuenta?",
    
    // Home Page & General Content
    homeTitle: "HuBiT - Hub de servicios comunitarios",
    homeDescription: "Hub de servicios comunitarios con pagos en criptomonedas",
    professionalServicesForHome: "Hub de servicios comunitarios",
    whoWeAreTitle: "Quiénes Somos",
    whoWeAreIntro: "Somos una plataforma integral que conecta a administradores de fincas, empresas de servicios y vecinos para brindar transparencia en las necesidades de las comunidades de vecinos.",
    whoWeAreSummary: "Plataforma digital que conecta administradores de fincas, empresas de servicios y vecinos. Facilitamos la gestión transparente de comunidades mediante herramientas intuitivas, sistema de valoraciones verificadas y comunicación directa. Transformamos la administración tradicional en un ecosistema colaborativo donde todos se benefician: mejor gestión, servicios de calidad y comunidades más satisfechas.",
    ourMission: "Nuestra Misión",
    ourMissionText: "Nuestra misión es facilitar la comunicación, valoración y gestión de servicios, ayudando a las empresas a expandir su negocio mientras ofrecemos total transparencia a las comunidades.",
    ourEcosystem: "Nuestro Ecosistema",
    ourEcosystemText: "Creamos un ecosistema donde todos los participantes se benefician: los administradores pueden gestionar eficientemente las necesidades de sus comunidades, las empresas de servicios pueden mostrar su profesionalidad y obtener nuevos clientes, y los vecinos pueden valorar los servicios recibidos con total transparencia.",
    ourFundamentalValue: "Nuestro Valor Fundamental",
    ourFundamentalValueText: "La transparencia es nuestro valor fundamental, permitiendo que todas las partes involucradas tengan acceso a la información relevante, facilitando la toma de decisiones y mejorando la calidad de vida en las comunidades de vecinos.",
    howItWorksTitle: "Cómo Funciona",
    howItWorksIntro: "Nuestra plataforma funciona como un ecosistema integrado que conecta a los tres pilares fundamentales de las comunidades de vecinos:",
    forAdministrators: "Para Administradores",
    forAdministratorsText: "Ofrecemos herramientas digitales que simplifican la gestión diaria, permitiendo identificar necesidades, solicitar presupuestos y coordinar servicios desde un único panel de control intuitivo.",
    forServiceCompanies: "Para Empresas de Servicios",
    forServiceCompaniesText: "Proporcionamos un escaparate digital donde mostrar su profesionalidad, recibir solicitudes de presupuestos y obtener valoraciones verificadas que impulsan su reputación.",
    forNeighbors: "Para Vecinos",
    forNeighborsText: "Facilitamos una plataforma donde pueden reportar incidencias, seguir su resolución en tiempo real y valorar los servicios recibidos con total transparencia.",
    ratingsSystem: "Sistema de Valoraciones",
    ratingsSystemText: "Implementamos un sistema de evaluación que permite a los vecinos calificar los servicios, generando confianza y ayudando a tomar decisiones informadas.",
    virtuousCircle: "Esta integración crea un círculo virtuoso donde todos los participantes se benefician: mejores servicios para las comunidades, más oportunidades de negocio para los proveedores y una gestión más eficiente para los administradores.",
    ourAchievementsTitle: "Nuestros Logros",
    ourAchievementsIntro: "Desde el lanzamiento de nuestra plataforma, hemos logrado importantes avances que demuestran el impacto positivo de nuestro enfoque en la gestión de comunidades:",
    connectedCommunities: "Comunidades conectadas",
    connectedCommunitiesText: "Nuestra plataforma ya está siendo utilizada por cientos de comunidades de vecinos en todo el país.",
    verifiedCompanies: "Empresas verificadas",
    verifiedCompaniesText: "Contamos con una amplia red de proveedores de servicios de calidad que han pasado por nuestro proceso de verificación.",
    satisfactionIndex: "Índice de satisfacción",
    satisfactionIndexText: "Las valoraciones de los usuarios muestran un alto nivel de satisfacción con la plataforma y los servicios.",
    resolvedIncidents: "Incidencias resueltas",
    resolvedIncidentsText: "Hemos facilitado la resolución eficiente de miles de incidencias en comunidades, mejorando la calidad de vida.",
    achievementsConclusion: "Estos logros reflejan nuestro compromiso con la creación de un ecosistema transparente y eficiente que beneficia a todos los participantes: administradores, empresas de servicios y vecinos.",
    luxuryResidences: "Residencias de Lujo",
    luxuryResidencesDesc: "Comunidades de vecinos exclusivas",
    whoWeAre: "Quiénes Somos",
    howItWorks: "Cómo Funciona",
    achievements: "Nuestros Logros",
    features: "Características",

    // User Roles & Dashboards
    communityMember: "Miembro de la Comunidad",
    serviceProvider: "Proveedor de Servicios",
    estateAdministrator: "Administrador de Fincas",
    particular: "Particular",
    welcomeToDashboard: "Bienvenido al Panel de Control",
    selectUserType: "Selecciona tu tipo de usuario",
    selectUserTypeDesc: "Elige la opción que mejor describa tu perfil para acceder a las funcionalidades específicas",
    whatsYourRole: "¿Cuál es tu rol?",
    communityMemberDesc: "Accede a servicios exclusivos para tu comunidad",
    serviceProviderDesc: "Gestiona tus servicios y clientes",
    estateAdministratorDesc: "Administra propiedades y comunidades",
    particularDesc: "Servicios personalizados para particulares",
    accessDashboard: "Acceder al Panel",
    communityDashboard: "Panel de Comunidad",
    providerDashboard: "Panel de Proveedor",
    adminDashboard: "Panel de Administrador",
    particularDashboard: "Panel Particular",
    controlPanel: "Panel de Control",

    // Services
    plumbing: "Fontanería",
    electrical: "Electricidad",
    painting: "Pintura",
    carpentry: "Carpintería",
    maintenance: "Mantenimiento",
    cleaning: "Limpieza",
    security: "Seguridad",
    gardening: "Jardinería",
    masonry: "Albañilería",
    roofing: "Techado",
    generalRepairs: "Reparaciones Generales",
    roofTiles: "Tejas y Techado",
    movingServices: "Servicios de Mudanza",
    locksmith: "Cerrajería",
    cableTV: "Televisión por Cable",
    packageDelivery: "Entrega de Paquetes",
    hairdressing: "Peluquería",
    catering: "Catering",
    flooring: "Suelos",
    hvac: "Climatización",
    applianceRepair: "Reparación de Electrodomésticos",
    homeNetworking: "Redes Domésticas",
    restoration: "Restauración",
    deepCleaning: "Limpieza Profunda",
    interiorDecoration: "Decoración Interior",
    completeRenovation: "Renovación Completa",
    landscaping: "Paisajismo",
    waterHeating: "Calefacción de Agua",
    emergencyService: "Servicio de Emergencia",
    other: "Otro",
    
    // Service Provider Specific
    serviceProviderPortal: "Portal de Proveedor de Servicios",
    dashboardTitle: "Panel de Control",
    dashboardDesc: "Gestiona tus servicios y clientes",
    dashboardText: "Accede a tu panel de control para gestionar servicios, ver solicitudes y administrar tu perfil profesional.",
    openDashboard: "Abrir Panel de Control",
    serviceProfile: "Perfil de Servicios",
    manageOfferings: "Gestiona tus ofertas",
    serviceProfileText: "Configura y gestiona tu perfil de servicios para mostrar tu experiencia y especialidades.",
    popularCategories: "Categorías Populares",
    activeBids: "Licitaciones Activas",
    bidManagement: "Gestión de Licitaciones",
    serviceCategories: "Categorías de Servicios",
    professionalProfile: "Perfil Profesional",
    businessHours: "Horario de Trabajo",
    serviceArea: "Área de Servicio",
    pricing: "Precios",
    portfolio: "Portafolio",
    certifications: "Certificaciones",
    workExperience: "Experiencia Laboral",
    specializations: "Especializaciones",
    equipment: "Equipamiento",
    availability: "Disponibilidad",
    emergencyServices: "Servicios de Emergencia",
    weekendAvailability: "Disponibilidad Fines de Semana",
    holidayServices: "Servicios en Festivos",
    serviceOverview: "Resumen de Servicios",
    bids: "Licitaciones",
    communityRequests: "Solicitudes de la Comunidad",
    requests: "Solicitudes",
    editBid: "Editar Licitación",
    contactClient: "Contactar Cliente",
    submitBid: "Enviar Licitación",
    noRequests: "No hay solicitudes disponibles",
    browseAllRequests: "Explorar Todas las Solicitudes",
    overview: "Resumen",
    companyInformation: "Información de la Empresa",
    companyName: "Nombre de la Empresa",
    taxId: "NIF/CIF",
    businessAddress: "Dirección Comercial",
    website: "Sitio Web",
    companyDescription: "Descripción de la Empresa",
    saveChanges: "Guardar Cambios",
    servicesOffered: "Servicios Ofrecidos",
    editServices: "Editar Servicios",
    certificationsLicenses: "Certificaciones y Licencias",
    addCertification: "Agregar Certificación",
    professionalLicense: "Licencia Profesional",
    validUntil: "Válido hasta",
    verified: "Verificado",
    insuranceCertificate: "Certificado de Seguro",
    coverage: "Cobertura",
    qualityCertification: "Certificación de Calidad",
    addPhoto: "Agregar Foto",
    change: "Cambiar",
    details: "Detalles",
    uploadPhoto: "Subir Foto",
    recentReviews: "Reseñas Recientes",
    viewAllReviews: "Ver Todas las Reseñas",
    weekAgo: "semana atrás",
    daysAgo: "días atrás",
    quickStats: "Estadísticas Rápidas",
    completedJobs: "Trabajos Completados",
    responseTime: "Tiempo de Respuesta",
    memberSince: "Miembro desde",
    viewPublicProfile: "Ver Perfil Público",
    vsLastWeek: "vs semana pasada",
    thisMonth: "este mes",
    reviews: "reseñas",
    upcomingAppointments: "Próximas Citas",
    noUpcomingAppointments: "No hay citas próximas",
    currentBidsFor: "Licitaciones Actuales para",
    communityRequestsFor: "Solicitudes de la Comunidad para",
    noBidsInCategory: "No hay licitaciones en esta categoría",
    noRequestsInCategory: "No hay solicitudes en esta categoría",
    budget: "Presupuesto",

    // Particular Dashboard
    myProfile: "Mi Perfil",
    personalInformation: "Información Personal",
    fullNameLabel: "Nombre Completo",
    emailLabel: "Correo Electrónico",
    phoneLabel: "Teléfono",
    locationLabel: "Ubicación",
    editProfile: "Editar Perfil",
    individual: "Particular",
    requestQuote: "Solicitar Presupuesto",
    serviceType: "Tipo de Servicio",
    selectServiceType: "Seleccionar tipo de servicio",
    preferredDate: "Fecha Preferida",
    serviceTitle: "Título del Servicio",
    exampleLeakRepair: "Ej. Reparación de fuga en el baño",
    detailedDescription: "Descripción Detallada",
    describeServiceNeeded: "Describe el servicio que necesitas",
    requestQuotes: "Solicitar Presupuestos",
    searchProviders: "Buscar Proveedores",
    viewProfile: "Ver Perfil",
    request: "Solicitar",
    loadMoreProviders: "Cargar Más Proveedores",
    myFavorites: "Mis Favoritos",
    noFavoriteProviders: "No tienes proveedores favoritos",
    addFavoriteProvidersDesc: "Añade proveedores a tus favoritos para acceso rápido",
    exploreProviders: "Explorar Proveedores",
    myProperties: "Mis Propiedades",
    addProperty: "Añadir Propiedad",
    editProperty: "Editar Propiedad",
    deleteProperty: "Eliminar Propiedad",
    propertyType: "Tipo de Propiedad",
    propertyAddress: "Dirección de la Propiedad",
    city: "Ciudad",
    postalCode: "Código Postal",
    propertySize: "Tamaño de la Propiedad",
    bedrooms: "Dormitorios",
    bathrooms: "Baños",
    yearBuilt: "Año de Construcción",
    propertyDescription: "Descripción de la Propiedad",
    propertyStatus: "Estado de la Propiedad",
    owned: "Propiedad",
    rented: "Alquilado",
    vacant: "Vacante",
    apartment: "Apartamento",
    house: "Casa",
    townhouse: "Casa Adosada",
    condo: "Piso",
    studio: "Estudio",
    selectProperty: "Seleccionar Propiedad",
    noPropertiesFound: "No se encontraron propiedades",
    addFirstProperty: "Añade tu primera propiedad",
    propertyManager: "Gestor de Propiedades",
    apartmentInCenter: "Apartamento en Centro",
    beachHouse: "Casa en la Playa",
    manage: "Gestionar",
    notifications: "Notificaciones",
    quoteReceived: "Presupuesto Recibido",
    quoteReceivedDesc: "Has recibido un nuevo presupuesto para tu solicitud",
    hoursAgo: "hace 2 horas",
    viewQuote: "Ver Presupuesto",
    serviceCompleted: "Servicio Completado",
    serviceCompletedDesc: "El servicio de fontanería ha sido completado",
    yesterday: "ayer",
    rateService: "Valorar Servicio",
    viewAllNotifications: "Ver Todas las Notificaciones",
    configuration: "Configuración",
    accountPreferences: "Preferencias de Cuenta",
    language: "Idioma",
    spanish: "Español",
    english: "Inglés",
    catalan: "Catalán",
    emailNotifications: "Notificaciones por Email",
    pushNotifications: "Notificaciones Push",
    smsNotifications: "Notificaciones SMS",
    privacy: "Privacidad",
    profileVisibleToProviders: "Perfil visible para proveedores",
    shareServiceHistory: "Compartir historial de servicios",
    changePassword: "Cambiar Contraseña",
    setupTwoFactor: "Configurar Autenticación de Dos Factores",
    manageConnectedDevices: "Gestionar Dispositivos Conectados",
    dataAndPrivacy: "Datos y Privacidad",
    downloadMyData: "Descargar Mis Datos",
    deleteMyAccount: "Eliminar Mi Cuenta",
    myPayments: "Mis Pagos",
    noPaymentHistory: "No hay historial de pagos disponible",
    recommendations: "Recomendaciones",
    noRecommendations: "No hay recomendaciones disponibles",
    myAwards: "Mis Premios",
    noAwards: "No hay premios disponibles",
    unit: "Unidad",
    noPropertySelected: "No hay propiedad seleccionada",
    propertySelected: "Propiedad seleccionada",
    selectAPropertyToManage: "Selecciona una propiedad para gestionar",
    changeProperty: "Cambiar Propiedad",
    noServiceHistoryMessage: "Aún no has utilizado ningún servicio",

    // Financial
    paymentSystemTitle: "Sistema de Pagos Híbrido",
    paymentSystemIntro: "Ofrecemos múltiples opciones de pago para adaptarnos a las preferencias de todos nuestros usuarios",
    fiatCurrencies: "Monedas FIAT",
    fiatDescription: "Métodos de pago tradicionales y seguros",
    cryptocurrencies: "Criptomonedas",
    cryptoDescription: "Pagos descentralizados con las principales criptomonedas",
    bitcoin: "Bitcoin (BTC)",
    ethereum: "Ethereum (ETH)",
    binanceCoin: "Binance Coin (BNB)",
    solana: "Solana (SOL)",
    hubitToken: "Token HUBIT",
    hbitDescription: "Nuestro token nativo con beneficios exclusivos",
    acceptedPayments: "Tipos de Pagos Aceptados",
    p2pPayments: "Persona a Persona",
    p2bPayments: "Persona a Empresa",
    b2pPayments: "Empresa a Persona",
    b2bPayments: "Empresa a Empresa",
    howToBuyHbitTitle: "Cómo Comprar HBIT",
    howToBuyHbitIntro: "Sigue estos sencillos pasos para adquirir tokens HBIT y acceder a beneficios exclusivos",
    hbitBenefits: "Beneficios de usar HBIT",
    benefit1: "Descuentos Exclusivos",
    benefit2: "Transacciones Rápidas",
    benefit3: "Recompensas por Fidelidad",
    benefit4: "Acceso Prioritario",
    startUsingHbit: "Comenzar a usar HBIT",
    learnMore: "Saber más",
    
    // Community & Particular Member Dashboards (Shared)
    serviceHistory: "Historial de Servicios",
    rateThisService: "Valorar este Servicio",
    serviceRating: "Valoración del Servicio",
    overallSatisfaction: "Satisfacción General",
    serviceQuality: "Calidad del Servicio",
    timeliness: "Puntualidad",
    professionalism: "Profesionalidad",
    valueForMoney: "Relación Calidad-Precio",
    wouldRecommend: "¿Recomendarías este servicio?",
    addComment: "Añadir Comentario",
    commentPlaceholder: "Comparte tu experiencia con este servicio...",
    submitRating: "Enviar Valoración",
    editRating: "Editar Valoración",
    deleteRating: "Eliminar Valoración",
    ratingSubmitted: "Valoración enviada",
    thankYouForRating: "Gracias por tu valoración",
    noServicesToRate: "No tienes servicios para valorar",
    noServiceHistory: "No tienes historial de servicios",
    completedServices: "Servicios Completados",
    pendingServices: "Servicios Pendientes",
    cancelledServices: "Servicios Cancelados",
    filterByStatus: "Filtrar por Estado",
    filterByCategory: "Filtrar por Categoría",
    sortByDate: "Ordenar por Fecha",
    sortByRating: "Ordenar por Valoración",
    mostRecent: "Más Reciente",
    oldest: "Más Antiguo",
    highestRated: "Mejor Valorado",
    lowestRated: "Peor Valorado",
    allCategories: "Todas las Categorías",
    allStatuses: "Todos los Estados",
    serviceDate: "Fecha del Servicio",
    serviceCost: "Coste del Servicio",
    providerName: "Nombre del Proveedor",
    yourRating: "Tu Valoración",
    notRated: "Sin Valorar",
    rateNow: "Valorar Ahora",
    viewDetails: "Ver Detalles",
    contactProvider: "Contactar Proveedor",
    repeatService: "Repetir Servicio",
    reportIssue: "Reportar Problema",
    serviceDetails: "Detalles del Servicio",
    serviceId: "ID del Servicio",
    scheduledFor: "Programado para",
    actualDate: "Fecha Real",
    duration: "Duración",
    materials: "Materiales",
    laborCost: "Coste de Mano de Obra",
    totalCost: "Coste Total",
    paymentMethod: "Método de Pago",
    invoiceNumber: "Número de Factura",
    warranty: "Garantía",
    followUpRequired: "Seguimiento Requerido",
    serviceNotes: "Notas del Servicio",
    beforePhotos: "Fotos Antes",
    afterPhotos: "Fotos Después",
    topRatedProviders: "Proveedores Mejor Valorados",
    recommendedForYou: "Recomendado para Ti",
    basedOnHistory: "Basado en tu historial",
    basedOnCommunityRatings: "Basado en las valoraciones de tu comunidad",
    similarServices: "Servicios Similares",
    recentlyUsed: "Usados Recientemente",
    popularInYourArea: "Popular en tu Zona",
    newProviders: "Nuevos Proveedores",
    specialOffers: "Ofertas Especiales",
    premiumProviders: "Proveedores Premium",
    emergencyAvailable: "Disponible para Emergencias",
    weekendService: "Servicio de Fin de Semana",
    sameDay: "Mismo Día",
    guaranteedService: "Servicio Garantizado",
    ratings: "Valoraciones",
    totalRatings: "Total de Valoraciones",
    averageRating: "Calificación Promedio",
    ratingBreakdown: "Desglose de Valoraciones",
    fiveStars: "5 Estrellas",
    fourStars: "4 Estrellas",
    threeStars: "3 Estrellas",
    twoStars: "2 Estrellas",
    oneStar: "1 Estrella",
    mostHelpfulReviews: "Reseñas Más Útiles",
    verifiedCustomer: "Cliente Verificado",
    helpfulReview: "Reseña Útil",
    reportReview: "Reportar Reseña",
    sortReviews: "Ordenar Reseñas",
    newestFirst: "Más Nuevas Primero",
    oldestFirst: "Más Antiguas Primero",
    highestRatedFirst: "Mejor Valoradas Primero",
    lowestRatedFirst: "Peor Valoradas Primero",
    yes: "Sí",
    no: "No",
    "Muy Insatisfecho": "Muy Insatisfecho",
    "Insatisfecho": "Insatisfecho",
    "Neutral": "Neutral",
    "Satisfecho": "Satisfecho",
    "Muy Satisfecho": "Muy Satisfecho",
    "Selecciona una puntuación": "Selecciona una puntuación",
    jobs: "trabajos",
    properties: "Propiedades",

    // Community Member Dashboard Specific
    availableServices: "Servicios Disponibles",
    requestService: "Solicitar Servicio",
    myRequests: "Mis Solicitudes",
    communityNews: "Noticias de la Comunidad",
    myServices: "Mis Servicios",
    serviceRequests: "Solicitudes de Servicio",
    earnings: "Ganancias",
    schedule: "Horario",
    clients: "Clientes",
    addService: "Añadir Servicio",
    manageServices: "Gestionar Servicios",
    financialReports: "Informes Financieros",
    communications: "Comunicaciones",
    manageResidents: "Gestionar Residentes",
    findServices: "Encontrar Servicios",
    myBookings: "Mis Reservas",
    favoriteProviders: "Proveedores Favoritos",
    bookService: "Reservar Servicio",
    searchServices: "Buscar Servicios",
    communityMemberDashboard: "Panel de Miembro de la Comunidad",
    communityChat: "Chat de la Comunidad",
    scheduleVideoConference: "Programar Videoconferencia",
    informIssue: "Informar Incidencia",
    communityContracts: "Contratos de la Comunidad",
    communityBudget: "Presupuesto de la Comunidad",
    contactAdministrator: "Contactar Administrador",
    serviceRatings: "Valoraciones de Servicios",
    elevatorMaintenance: "Mantenimiento de Ascensor",
    gatesCleaning: "Limpieza de Portales",
    commonAreasGardening: "Jardinería de Áreas Comunes",
    lightingRepair: "Reparación de Iluminación",
    excellentCommunityServiceComment: "Servicio excelente para toda la comunidad",
    goodWorkStairsComment: "Buen trabajo general, podrían mejorar en escaleras",
    preventiveMaintenance: "Mantenimiento preventivo",
    urgentRepairs: "Reparaciones urgentes",
    modernization: "Modernización",
    landscapeDesign: "Diseño paisajístico",
    irrigationSystems: "Sistemas de riego",
    gatesDisinfection: "Desinfección de portales",
    maintenanceSpec: "Mantenimiento",
    
    // Property Selection
    communityMemberProperties: "Propiedades del Miembro de la Comunidad",
    particularProperties: "Propiedades del Particular",
    selectPropertyDescription: "Selecciona una de tus propiedades para gestionarla.",
    selectPropertyToAccess: "Selecciona la propiedad a la que deseas acceder para gestionar todos los servicios e información relacionados.",
    searchProperties: "Buscar por nombre o dirección...",
    noPropertiesFoundDescription: "Parece que todavía no has añadido ninguna propiedad.",

    // Whitepaper
    whitepaperTitle: "Whitepaper HuBiT",
    whitepaperSubtitle: "Gestión Descentralizada de Propiedades en Solana",
    executiveSummary: "Resumen Ejecutivo",
    executiveSummaryText: "HuBiT es un token de utilidad construido en Solana que conecta administradores de propiedades, proveedores de servicios y residentes en un ecosistema transparente. Al mantener HuBiT, los usuarios acceden a funciones premium, mientras que el token financia el crecimiento de la plataforma sin intermediarios.",
    whySolana: "¿Por qué Solana?",
    lowFees: "Tarifas bajas por transacción",
    highSpeed: "TPS Alta velocidad",
    massAdoption: "Listo para adopción masiva",
    tokenomics: "Tokenómica",
    tokenDetails: "Detalles del Token",
    tokenName: "Nombre:",
    blockchain: "Blockchain:",
    totalSupply: "Suministro Total:",
    contract: "Contrato:",
    toBeDeployed: "[Por desplegar]",
    distribution: "Distribución",
    teamAdvisors: "Equipo y Asesores",
    communityRewards: "Comunidad y Recompensas",
    ecosystemFund: "Fondo del Ecosistema",
    publicCirculation: "Circulación Pública",
    utility: "Utilidad",
    holdHubit: "Mantener 100 HuBiT:",
    holdHubitDesc: "App sin anuncios, derechos de voto, funciones premium",
    payAsYouGo: "Pago por uso:",
    payAsYouGoDesc: "€1.99/mes para no poseedores",
    staking: "Staking:",
    stakingDesc: "Gana recompensas por bloquear tokens (fase futura)",
    roadmap: "Hoja de Ruta",
    q3Title: "Q3 2025",
    mvpDevelopment: "Desarrollo MVP:",
    mvpDevelopmentDesc: "Demo de la app HuBiT",
    brandLaunch: "Lanzamiento de Marca:",
    brandLaunchDesc: "Sitio web + Twitter",
    tokenDeployment: "Despliegue del Token:",
    tokenDeploymentDesc: "Creación del token SPL en Solana",
    q4Title: "Q4 2025",
    appBetaRelease: "Lanzamiento Beta de la App:",
    appBetaReleaseDesc: "iOS/Android (funciones de gestión de propiedades, integración de billetera Solana)",
    listings: "Listados:",
    listingsDesc: "CoinMarketCap, CoinGecko, exchanges centralizados y descentralizados",
    partnerships: "Asociaciones:",
    partnershipsDesc: "50+ proveedores de servicios incorporados",
    q1Title: "Q1 2026",
    globalExpansion: "Expansión Global:",
    globalExpansionDesc: "Campañas de mercado internacional",
    tenThousandUsers: "10,000+ Users:",
    tenThousandUsersDesc: "Incentivized via airdrops and community rewards",
    governanceDao: "DAO de Gobernanza:",
    governanceDaoDesc: "Token holders vote on platform upgrades",
    joinCommunity: "Join our community and be part of the future of property management",
    followTwitter: "Follow us on Twitter",
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("es");

  const t = useCallback(
    (key: string, langOverride?: Language) => {
      const lang = langOverride || language;
      const keys = key.split(".");
      let result: any = translations[lang];
      for (const k of keys) {
        result = result?.[k];
        if (result === undefined) {
          // Fallback to English if translation is missing
          let fallbackResult: any = translations.en;
          for (const fk of keys) {
            fallbackResult = fallbackResult?.[fk];
          }
          return fallbackResult || key;
        }
      }
      return result || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
