// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djkrzbmgzfwagmripozi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqa3J6Ym1nemZ3YWdtcmlwb3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjIyODgsImV4cCI6MjA2Njc5ODI4OH0.P6gVuh5Vi-EP9hSm1WooCXjJKiy8sCl4wZcC_N2KehY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

/**
 * Check if Supabase is properly configured with valid credentials
 */
export const isSupabaseConfigured = (): boolean => {
  return !!(
    SUPABASE_URL && 
    SUPABASE_URL !== 'invalid_supabase_url' &&
    SUPABASE_PUBLISHABLE_KEY && 
    SUPABASE_PUBLISHABLE_KEY !== 'invalid_anon_key' &&
    SUPABASE_URL.startsWith('https://') &&
    SUPABASE_PUBLISHABLE_KEY.length > 50
  );
};